 SELECT OSA.CODFIL, OSA.CODOSA CODIGO, OSA.CODCTS, OSA.CODCLIFOR, IOS.CODPRO, CLI.RAZSOC, PRO.DESCRI DESCRI_PRODUTO, PRO.REFERE,
OSA.STSCNF AS SITDOC
FROM WMSOSA OSA
INNER JOIN WMSIOS IOS ON OSA.CODOSA=IOS.CODOSA AND OSA.CODFIL=IOS.FILOSA
--INNER JOIN WMSIOL IOL ON IOS.ID_IOS=IOL.ID_IOS
INNER JOIN RODCLI CLI ON CLI.CODCLIFOR=OSA.CODCLIFOR
INNER JOIN WMSPRO PRO ON PRO.CODIGO=IOS.CODPRO
WHERE OSA.CODCTS=147 AND OSA.STSCNF='R' --AND OSA.CODOSA=56859 --AND OSA.SITUAC<>'C' AND OSA.SITUAC='I' AND ISNULL(OSA.STSCNF,'')='A'

--SITUAC
--E: EM SEPARAÇÃO
--C: CONFERIDO
--A: AGUARDANDO SEPARAÇÃO
--R: AGUARDANDO CARREGAMENTO
