SELECT
CT.CODIGO, CT.NUMVIA, CT.SITCIO, CT.SITUAC,
TAB.CODFIL, TAB.SERIE, TAB.NUMERO, TAB.NUMDOC, TAB.CODCLIFOR, CT.DATSAI, TAB.VLRLIQ
FROM
(
SELECT NULL AS NUMLAN, 
--CT.NUMVIA, CT.SITCIO, CT.SITUAC,  
I.CODCLIFOR, I.SERIE, I.NUMDOC, I.NUMPAR,D.CODFIL, I.SITUAC,D.TIPDOC, NULL AS CODHISPG, NULL AS CODTAX, NULL AS FILCHE, BCOABA AS BANCHE, 
NULL AS NUMCHE, CONABA AS NUMECC, NULL AS DATLAN, I.DATVEN, NULL AS DEBCRE, NULL AS VLRLAN,  I.DESIR, I.DESISS, NULL AS DESPIS,  I.VLRDES,  
I.VLRJUR, I.VLRCOR, I.VLRLIQ, I.REFERE AS OBSERV,  I.DATATU,   I.USUATU, NULL AS ORIGEM, I.FORDES, I.DOCDES, NULL AS SERDES,  I.DESCOB,  
I.DESINS,  I.DATINC,NULL AS HISTORICO, CONABA AS CONTA,B.DESCRI AS BANCO,'EM ABERTO' AS TIPO  ,BCOABA,AGEABA,CONABA,CGCABA,FAVABA,
CASE
WHEN I.NUMDOC LIKE '%CTBA' THEN REPLACE(I.NUMDOC, 'CTBA', '') 
WHEN I.NUMDOC LIKE '%CTBB' THEN REPLACE(I.NUMDOC, 'CTBB', '')
WHEN I.NUMDOC LIKE '%CTBC' THEN REPLACE(I.NUMDOC, 'CTBC', '')
WHEN I.NUMDOC LIKE '%CTBD' THEN REPLACE(I.NUMDOC, 'CTBD', '')
WHEN I.NUMDOC LIKE '%CTBE' THEN REPLACE(I.NUMDOC, 'CTBE', '')
WHEN I.NUMDOC LIKE '%CTBF' THEN REPLACE(I.NUMDOC, 'CTBF', '')
WHEN I.NUMDOC LIKE '%CTBT' THEN REPLACE(I.NUMDOC, 'CTBT', '') ELSE I.NUMDOC END NUMERO
FROM PAGDOCI I 
INNER JOIN PAGDOC D ON D.CODCLIFOR=I.CODCLIFOR AND D.SERIE=I.SERIE  AND D.NUMDOC=I.NUMDOC  
LEFT OUTER JOIN RODBCO B ON B.CODBCO=D.BCOABA
WHERE I.SITUAC = 'D'     AND D.SERIE = 'CTB'    --AND D.CODCLIFOR = 6682017
--AND (I.NUMDOC IN ('29999','29999CTBA','29999CTBB','29999CTBC','29999CTBD','29999CTBE','29999CTBF','29999CTBT') 
--OR (D.CODCFR = 29999 AND D.SERCFR = 'CTB' AND D.FILCFR = 10 AND TIPCFR = 'F')) 
AND I.DATINC >= '2023-01-01'  AND  I.DATINC <= '2023-03-09'
) TAB
LEFT OUTER JOIN RODCFR CT ON CT.SERSUB=TAB.SERIE AND TAB.CODFIL=CT.CODFIL AND CT.CODIGO=TAB.NUMERO
WHERE CODIGO=10933
ORDER BY CT.DATSAI ASC
