SELECT WMSIEN.*, WMSPRO.DESCRI AS DESCRI_PRO, UAM.DESCRI DESCRI_UAM,
WMSIEN.QUANTI
-
(
	SELECT sum(QUANTI)
	FROM wmslen
	WHERE wmslen.ID_IEN=WMSIEN.ID_IEN
) AS VLR_CONF,
WMSPRO.CODAUX CODAUX
FROM WMSIEN
INNER JOIN WMSPRO ON WMSPRO.CODIGO=WMSIEN.CODPRO
LEFT OUTER JOIN WMSUAM UAM ON UAM.CODUAM=WMSIEN.CODUAM
WHERE WMSIEN.CODENF=17892 AND WMSIEN.CODFIL=4
ORDER BY WMSIEN.ID_IEN DESC