SELECT DISTINCT NFC.CODFIL, NFC.SERCON, NFC.CODCON, ANE.DATINC, ANE.CANEXO, MAN.CODFIL, MAN.SERMAN, MAN.CODMAN,
MOT.NOMMOT, ANE.USUINC, CLI.CODMUN, MUN.ESTADO,
CASE OCH.CODOCO
	WHEN 100 THEN OCH.CODOCO
	WHEN 109 THEN OCH.CODOCO
	WHEN 110 THEN OCH.CODOCO
	WHEN 116 THEN OCH.CODOCO
	WHEN 129 THEN OCH.CODOCO
	WHEN 130 THEN OCH.CODOCO
	WHEN 211 THEN OCH.CODOCO
	WHEN 246 THEN OCH.CODOCO
	ELSE NULL
END AS CODOCO,
URC.CODRMC, URC.CODFIL_RMC, URC.SITUAC_RMC
FROM RODANE ANE
INNER JOIN RODNFC NFC ON ANE.CODIGO=NFC.ID_NFC AND ANE.KEYC2=NFC.NOTFIS
LEFT OUTER JOIN RODIMA IMA ON NFC.CODCON=IMA.CODDOC AND NFC.SERCON=IMA.SERDOC AND NFC.CODFIL=IMA.FILDOC
LEFT OUTER JOIN RODMAN MAN ON IMA.CODMAN=MAN.CODMAN AND IMA.FILMAN=MAN.CODFIL AND IMA.SERMAN=MAN.SERMAN
LEFT OUTER JOIN RODMOT MOT ON MAN.CODMO1=MOT.CODMOT
LEFT OUTER JOIN RODCON CON ON NFC.CODCON=CON.CODCON AND NFC.SERCON=CON.SERCON AND NFC.CODFIL=CON.CODFIL
LEFT OUTER JOIN RODCLI CLI ON CLI.CODCLIFOR=CASE WHEN CON.TERCOL IS NULL THEN CON.CODREM ELSE CON.TERCOL END
LEFT OUTER JOIN RODMUN MUN ON CLI.CODMUN=MUN.CODMUN
LEFT OUTER JOIN RODOCH OCH ON NFC.ID_NFC=OCH.ID_NFC
LEFT OUTER JOIN VW_ULTIMO_ROMANEIO_CARGA URC ON NFC.CODFIL=URC.FILIAL AND NFC.SERCON=URC.SERIE AND NFC.CODCON=URC.CODIGO
WHERE ANE.CANEXO NOT LIKE 'A_%' AND ANE.USUINC IS NOT NULL AND ANE.ROTINA='NFC' AND ANE.DATINC>'2022-04-30' AND
ANE.DATINC<'2022-06-01' AND MAN.CODMAN IS NULL