SELECT NFC.CODFIL AS FILIAL, NFC.SERCON AS SERIE, NFC.CODCON AS CODIGO, NFC.NOTFIS, NFC.SERIEN, OCH.OBSERV, OCH.CODOBS, OBE.DESCRI AS OBSERVACAO, OCH.CODOCO, OCO.DESCRI AS OCORENCIA, OCH.USUATU, OCH.DATATU, OCH.TIPDOC
FROM RODOCH OCH
INNER JOIN RODNFC NFC ON OCH.ID_NFC=NFC.ID_NFC
LEFT OUTER JOIN RODOBE OBE ON OCH.CODOBS=OBE.CODOBS
LEFT OUTER JOIN RODOCO OCO ON OCH.CODOCO=OCO.CODIGO
WHERE OCH.OBSERV LIKE '%REDESPACHO%' AND OCH.TIPDOC='CTR'

UNION ALL

SELECT IOS.FILORD AS FILIAL, IOS.SERORD AS SERIE, IOS.CODORD AS CODIGO, IOS.NOTFIS, IOS.SERIEN, OCH.OBSERV, OCH.CODOBS, OBE.DESCRI AS OBSERVACAO, OCH.CODOCO, OCO.DESCRI AS OCORENCIA, OCH.USUATU, OCH.DATATU, OCH.TIPDOC
FROM RODOCH OCH
INNER JOIN RODIOS IOS ON OCH.ID_IOS=IOS.ID_IOS
LEFT OUTER JOIN RODOBE OBE ON OCH.CODOBS=OBE.CODOBS
LEFT OUTER JOIN RODOCO OCO ON OCH.CODOCO=OCO.CODIGO
WHERE OCH.OBSERV LIKE '%REDESPACHO%' AND OCH.TIPDOC='OST'