SELECT ORD.CODIGO AS 'CODORD', ORD. SERORD, ORD.CODFIL AS 'FILORD', ORD.DATEMI, ORD.CODPAG, CLI.RAZSOC, ORD.TOTFRE, ORD.SITUAC,
EST.CODIGO AS 'CODNOT', EST.SERSUB AS 'SERNOT', EST.CODFIL AS 'FILNOT'
FROM RODORD ORD
LEFT OUTER JOIN RODORN ORN ON ORD.CODIGO=ORN.CODORD AND ORD.SERORD=ORN.SERORD AND ORD.CODFIL=ORN.FILORD
LEFT OUTER JOIN ESTNOT EST ON ORN.CODNOT=EST.CODIGO AND ORN.SERNOT=EST.SERSUB AND ORN.FILNOT=EST.CODFIL
LEFT OUTER JOIN RODCLI CLI ON ORD.CODPAG=CLI.CODCLIFOR
WHERE ORD.TIPFAT='D' AND ORD.SITUAC<>'C'