SELECT MOT.NOMMOT, CFR.CODIGO AS 'CONTRATO', CFR.SERSUB AS 'SERIE CONTRATO', CFR.CODFIL AS 'FILIAL CONTRATO',
DCO.CODMAN AS 'MANIFESTO', DCO.SERMAN AS 'SERIE MAN', DCO.FILMAN AS 'FILIAL MAN',
DCO.CODDOC AS 'CTRC/OST', DCO.SERDOC AS 'SERIE DOC', DCO.FILDOC AS 'FILIAL DOC',
DCO.TIPDOC, CFR.SITUAC
FROM RODMOT MOT
LEFT OUTER JOIN RODCFR CFR ON MOT.CODMOT=CFR.CODMOT
LEFT OUTER JOIN RODDCO DCO ON CFR.CODIGO=DCO.CODIGO AND CFR.SERSUB=DCO.SERSUB AND CFR.CODFIL=DCO.CODFIL
WHERE MOT.CODMOT=2915 AND CFR.SITUAC<>'C'


SELECT TOP 1000 * FROM RODMAN
SELECT TOP 1000 * FROM RODCFR WHERE CODIGO=2 AND CODFIL=1 AND SERSUB='CTB'
SELECT TOP 1000 * FROM RODDCO WHERE CODIGO=26092
SELECT * FROM VW_SS_PESO_CONTRATOS WHERE SOMA_PESCFR IS NOT NULL AND CODMAN=126710 AND FILMAN=10 AND SERMAN='10' AND CODIGO_CFR=2 AND SERSUB='CTB' AND CODFIL_CFR=1

SELECT TOP 1000 * FROM RODIMA WHERE CODMAN=138609
SELECT * FROM RODLIN WHERE KMTPLA = 0
