--DASHBOARD RECEBIMENTOS
4.

--DASHBOARD VENDAS
SELECT
	RAZSOC, CLIPED, PEDIDO, OS, LEITURA, MATERIAL, TTPED, TTATE, CAST(CAST(DATPED AS DATE) AS VARCHAR) AS DATPED, AG_BDG
FROM VW_VENDA_BRIDGESTONE
WHERE LEITURA IN ('AGUARDANDO', 'SEPARAÇÃO', '2º LEITURA')
ORDER BY AG_BDG, RAZSOC

--DASHBOARD VENDAS FINALIZADAS
SELECT
	RAZSOC, CLIPED, PEDIDO, OS, LEITURA, MATERIAL, TTPED, TTATE, CAST(CAST(DATPED AS DATE) AS VARCHAR) AS DATPED, AG_BDG
FROM VW_VENDA_BRIDGESTONE
WHERE LEITURA IN ('2º LEITURA FINALIZADA', 'M51 PENDENTE')
ORDER BY RAZSOC

--DASHBOARD INDICADOR RECEBIMENTO
SELECT
	FORMAT(DAY(DTM41), '00') + '/' + FORMAT(MONTH(DTM41), '00') AS DATA_REF, CAST(DTM41 AS VARCHAR) AS DATE_FILTER,
	SUM(TOTAL_PROD) AS TOTAL_DIA
FROM VW_RECEBIMENTO_BRIDGESTONE
WHERE STATUS = 'M41 ENVIADO'
GROUP BY DTM41
ORDER BY DTM41

--DASHBOARD INDICADOR SEPARAÇÃO
SELECT
	FORMAT(DAY(CAST(DATM51 AS DATE)), '00') + '/' + FORMAT(MONTH(CAST(DATM51 AS DATE)), '00') AS DATA_REF,
	CAST(CAST(DATM51 AS DATE) AS VARCHAR) AS DATE_FILTER, SUM(TTATE) AS TOTAL_DIA
FROM VW_VENDA_BRIDGESTONE
WHERE LEITURA = 'M51 ENVIADO'
GROUP BY CAST(DATM51 AS DATE)
ORDER BY CAST(DATM51 AS DATE)

--DASHBOARD INDICADOR EXPEDIÇÃO
SELECT 
	FORMAT(DAY(CAST(DATREF AS DATE)), '00') + '/' + FORMAT(MONTH(CAST(DATREF AS DATE)), '00') AS DATA_REF,
	CAST(CAST(DATREF AS DATE) AS VARCHAR) AS DATE_FILTER, SUM(QUANTI) AS TOTAL_DIA
FROM RODRMC RMC
LEFT OUTER JOIN RODIRC IRC ON RMC.CODRMC = IRC.CODRMC AND RMC.CODFIL = IRC.FILRMC
WHERE RMC.CODFIL = 4 AND RMC.CODSETCL = 8
GROUP BY CAST(DATREF AS DATE)
ORDER BY CAST(DATREF AS DATE)

--DASHBOARD INDICADOR RECEBIMENTO TIPO PROD
SELECT
	DATA_REF, TIPPRO, SUM(CAST(QUANTI AS INT)) AS TOTAL
FROM (
	SELECT 
		CASE GRU.DESCRI
			WHEN 'BRIDGESTONE BANDA'
				THEN 'BANDA'
			WHEN 'BRIDGESTONE COXIM'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE EXTRUSADO'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE HDSS'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE LUBRIFICANTE'
				THEN 'COLA'
		END AS TIPPRO,
		IOS.QUANTI, CAST(VRB.DTM41 AS DATE) AS DATA_REF
	FROM VW_RECEBIMENTO_BRIDGESTONE VRB
	LEFT OUTER JOIN WMSIOS IOS ON VRB.CODOSA = IOS.CODOSA
	LEFT OUTER JOIN WMSPRO PRO ON IOS.CODPRO = PRO.CODIGO
	LEFT OUTER JOIN WMSGRU GRU ON PRO.CODGRU = GRU.CODGRU
	WHERE VRB.STATUS = 'M41 ENVIADO'
) TAB
GROUP BY DATA_REF, TIPPRO
ORDER BY DATA_REF

--DASHBOARD INDICADOR SEPARAÇÃO TIPO PROD
SELECT
	DATA_REF, TIPPRO, SUM(CAST(QUANTI AS INT)) AS TOTAL
FROM (
	SELECT 
		CASE GRU.DESCRI
			WHEN 'BRIDGESTONE BANDA'
				THEN 'BANDA'
			WHEN 'BRIDGESTONE COXIM'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE EXTRUSADO'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE HDSS'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE LUBRIFICANTE'
				THEN 'COLA'
		END AS TIPPRO,
		IOS.QUANTI, CAST(VVB.DATM51 AS DATE) AS DATA_REF
	FROM VW_VENDA_BRIDGESTONE VVB
	LEFT OUTER JOIN WMSIOS IOS ON VVB.OS = IOS.CODOSA
	LEFT OUTER JOIN WMSPRO PRO ON IOS.CODPRO = PRO.CODIGO
	LEFT OUTER JOIN WMSGRU GRU ON PRO.CODGRU = GRU.CODGRU
	WHERE VVB.LEITURA = 'M51 ENVIADO'
) TAB
GROUP BY DATA_REF, TIPPRO
ORDER BY DATA_REF

--DASHBOARD INDICADOR EXPEDIÇÃO TIPO PROD
SELECT
	DATA_REF, TIPPRO, SUM(CAST(QUANTI AS INT)) AS TOTAL
FROM (
	SELECT
		CASE GRU.DESCRI
			WHEN 'BRIDGESTONE BANDA'
				THEN 'BANDA'
			WHEN 'BRIDGESTONE COXIM'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE EXTRUSADO'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE HDSS'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE LUBRIFICANTE'
				THEN 'COLA'
		END AS TIPPRO,
		IPE.QUANTI, CAST(RMC.DATREF AS DATE) AS DATA_REF
	FROM RODRMC RMC
	LEFT OUTER JOIN RODIRC IRC ON RMC.CODRMC = IRC.CODRMC AND RMC.CODFIL = IRC.FILRMC
	LEFT OUTER JOIN WMSIPE IPE ON IRC.CODDOC = IPE.CODIGO AND IRC.FILDOC = IPE.CODFIL
	LEFT OUTER JOIN WMSPRO PRO ON IPE.CODPRO = PRO.CODIGO
	LEFT OUTER JOIN WMSGRU GRU ON PRO.CODGRU = GRU.CODGRU
	WHERE RMC.CODFIL = 4 AND RMC.CODSETCL = 8
) TAB
GROUP BY DATA_REF, TIPPRO
ORDER BY DATA_REF

--DASHBOARD EXPEDIÇÃO CLIENTE
SELECT
	DATA_REF, RAZSOC, TIPPRO, SUM(CAST(QUANTI AS INT)) AS TOTAL
FROM (
	SELECT
		CASE GRU.DESCRI
			WHEN 'BRIDGESTONE BANDA'
				THEN 'BANDA'
			WHEN 'BRIDGESTONE COXIM'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE EXTRUSADO'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE HDSS'
				THEN 'COXIM'
			WHEN 'BRIDGESTONE LUBRIFICANTE'
				THEN 'COLA'
		END AS TIPPRO,
		IPE.QUANTI, CAST(RMC.DATREF AS DATE) AS DATA_REF, CLI.RAZSOC
	FROM RODRMC RMC
	LEFT OUTER JOIN RODIRC IRC ON RMC.CODRMC = IRC.CODRMC AND RMC.CODFIL = IRC.FILRMC
	LEFT OUTER JOIN WMSIPE IPE ON IRC.CODDOC = IPE.CODIGO AND IRC.FILDOC = IPE.CODFIL
	LEFT OUTER JOIN WMSPRO PRO ON IPE.CODPRO = PRO.CODIGO
	LEFT OUTER JOIN WMSGRU GRU ON PRO.CODGRU = GRU.CODGRU
	LEFT OUTER JOIN WMSPED PED ON IPE.CODIGO = PED.CODIGO AND IPE.CODFIL = PED.CODFIL
	LEFT OUTER JOIN WMSOSA OSA ON PED.CODIGO = OSA.CODPED AND PED.CODFIL = OSA.FILPED
	LEFT OUTER JOIN RODCLI CLI ON OSA.CODPRO = CLI.CODCLIFOR
	WHERE RMC.CODFIL = 4 AND RMC.CODSETCL = 8
) TAB
WHERE DATA_REF = CAST(GETDATE() - 1 AS DATE)
GROUP BY DATA_REF, TIPPRO, RAZSOC
ORDER BY RAZSOC

--DASHBOARD KPI VENDAS
SELECT
	DATEDIFF(MINUTE, DATPED, DATM51) AS OCTM51, CAST(CAST(DATPED AS DATE) AS VARCHAR) AS DATAPED,
	CAST(CAST(DATM51 AS DATE) AS VARCHAR) AS DATA_REF, *
FROM VW_VENDA_BRIDGESTONE
WHERE LEITURA = 'M51 ENVIADO'

--DASHBOARD KPI RECEBIMENTO
SELECT
	DATEDIFF(MINUTE, DATPED_TIME, DTM41_TIME) AS OCTM41, CAST(DATPED AS VARCHAR) AS DATAPED,
	CAST(DTM41 AS VARCHAR) AS DATA_REF, *
FROM VW_RECEBIMENTO_BRIDGESTONE
WHERE STATUS = 'M41 ENVIADO'

--DASHBOARD KPI EXPEDIÇÃO
SELECT
	CAST(DATA_REF AS VARCHAR) AS DATA_REF, SUM(CAST(QUANTI AS INT)) AS TOTAL
FROM (
	SELECT IPE.QUANTI, CAST(RMC.DATREF AS DATE) AS DATA_REF
	FROM RODRMC RMC
	LEFT OUTER JOIN RODIRC IRC ON RMC.CODRMC = IRC.CODRMC AND RMC.CODFIL = IRC.FILRMC
	LEFT OUTER JOIN WMSIPE IPE ON IRC.CODDOC = IPE.CODIGO AND IRC.FILDOC = IPE.CODFIL
	WHERE RMC.CODFIL = 4 AND RMC.CODSETCL = 8
) TAB
GROUP BY DATA_REF
ORDER BY DATA_REF
