SELECT VWMAN.FILIAL, VWMAN.SERIE, VWMAN.CODIGO, VWMAN.SITUAC, VWMAN.DATINC, VWMAN.TIPDOC,
VWMAN.TIPMAN, CMO.CODCMO ,CMO.DESCRI AS 'TABELA DE FRETE',
CASE CMO.CODCMO	
	WHEN 6 THEN	
		CASE VWMAN.TIPMAN 
			WHEN 7 THEN VWMAN.FILMAN 
		END 
	WHEN 5 THEN 
		CASE WHEN VWMAN.DATEMI<VWRMC.DATREF THEN VWRMC.CODFIL_RMC 
		ELSE 000
		END
	END AS 'FILIAL MAN/RMC'
FROM VW_ULTIMO_MANIFESTO_X_DOC VWMAN
LEFT OUTER JOIN RODFRA FRA ON VWMAN.TABPAD=FRA.CODFRE
LEFT OUTER JOIN RODCMO CMO ON FRA.CODCMO=CMO.CODCMO
LEFT OUTER JOIN VW_ULTIMO_ROMANEIO_CARGA VWRMC
	ON VWMAN.FILIAL=VWRMC.FILIAL AND VWMAN.SERIE=VWRMC.SERIE AND VWMAN.CODIGO=VWRMC.CODIGO AND VWMAN.TIPDOC=VWRMC.TIPDOC
WHERE VWMAN.DATINC>='2022-06-23'
ORDER BY CODIGO, SERIE, FILIAL



SELECT * FROM RODCON WHERE DATINC>='2022-06-23'
SELECT * FROM VW_ULTIMO_MANIFESTO_X_DOC
SELECT * FROM VW_ULTIMO_ROMANEIO_CARGA