-- MODIFICADA DIA 14/09/2016 - GUSTAVO 
-- ADICIONADO OS NOVOS PNEUS PARA ATE 8 LINHAS DE EIXOS.
-- ALTERADO O TAMANHO MAXIMO DOS CAMPOS DE 1500 PARA 4000
-- MODIFICADA DIA 14/05/2019 - GUSTAVO 
-- ADICIONADO MAIS PNEUS

CREATE PROCEDURE [dbo].[SP_ESQUEMATICA_PNEUS_VEICULO]
@PARFRO  AS SMALLINT = 0,
@PARVEI  AS VARCHAR(8)    = '',
@NLINHAS AS SMALLINT      = 1
WITH RECOMPILE
AS
BEGIN
SET NOCOUNT ON
CREATE TABLE #TEMP_SP_ROD_RELACAO_ESQUEMATICA(
CODVEI VARCHAR(8) NULL,
TIPVEI VARCHAR(30) NULL,
NUMEIX SMALLINT NULL,
CODFRO SMALLINT NULL,
FROTA VARCHAR(40) NULL,
MARCA VARCHAR(40) NULL,
MODELO VARCHAR(40) NULL,
MOTORISTA VARCHAR(40) NULL,
EDE VARCHAR(11) NULL,
EDD VARCHAR(11) NULL,
ETEE1 VARCHAR(11) NULL,
ETEI1 VARCHAR(11) NULL,
ETDI1 VARCHAR(11) NULL,
ETDE1 VARCHAR(11) NULL,
ETEE2 VARCHAR(11) NULL,
ETEI2 VARCHAR(11) NULL,
ETDI2 VARCHAR(11) NULL,
ETDE2 VARCHAR(11) NULL,
ETEE3 VARCHAR(11) NULL,
ETEI3 VARCHAR(11) NULL,
ETDI3 VARCHAR(11) NULL,
ETDE3 VARCHAR(11) NULL,
ETEE4 VARCHAR(11) NULL,
ETEI4 VARCHAR(11) NULL,
ETDI4 VARCHAR(11) NULL,
ETDE4 VARCHAR(11) NULL,
ESTEP1 VARCHAR(11) NULL,
ESTEP2 VARCHAR(11) NULL,
ETE VARCHAR(11) NULL,
ETD VARCHAR(11) NULL,
EDE2 VARCHAR(11) NULL,
EDD2 VARCHAR(11) NULL,
ETEE5 VARCHAR(11) NULL,
ETEI5 VARCHAR(11) NULL,
ETDI5 VARCHAR(11) NULL,
ETDE5 VARCHAR(11) NULL,
ETEE6 VARCHAR(11) NULL,
ETEI6 VARCHAR(11) NULL,
ETDI6 VARCHAR(11) NULL,
ETDE6 VARCHAR(11) NULL,
LETEE1 VARCHAR(11) NULL,
LETEI1 VARCHAR(11) NULL,
LETDI1 VARCHAR(11) NULL,
LETDE1 VARCHAR(11) NULL,
LETEE5 VARCHAR(11) NULL,
LETEI5 VARCHAR(11) NULL,
LETDI5 VARCHAR(11) NULL,
LETDE5 VARCHAR(11) NULL,
LETEE6 VARCHAR(11) NULL,
LETEI6 VARCHAR(11) NULL,
LETDI6 VARCHAR(11) NULL,
LETDE6 VARCHAR(11) NULL,
LETEE4 VARCHAR(11) NULL,
LETEI4 VARCHAR(11) NULL,
LETDI4 VARCHAR(11) NULL,
LETDE4 VARCHAR(11) NULL,
LETEE3 VARCHAR(11) NULL,
LETEI3 VARCHAR(11) NULL,
LETDI3 VARCHAR(11) NULL,
LETDE3 VARCHAR(11) NULL,
LETEE2 VARCHAR(11) NULL,
LETEI2 VARCHAR(11) NULL,
LETDI2 VARCHAR(11) NULL,
LETDE2 VARCHAR(11) NULL,
LETEE7 VARCHAR(11) NULL,
ETEE7 VARCHAR(11) NULL,
ETEI7 VARCHAR(11) NULL,
LETEI7 VARCHAR(11) NULL,
LETDI7 VARCHAR(11) NULL,
ETDI7 VARCHAR(11) NULL,
ETDE7 VARCHAR(11) NULL,
LETDE7 VARCHAR(11) NULL,
LETEE8 VARCHAR(11) NULL,
ETEE8 VARCHAR(11) NULL,
ETEI8 VARCHAR(11) NULL,
LETEI8 VARCHAR(11) NULL,
LETDI8 VARCHAR(11) NULL,
ETDI8 VARCHAR(11) NULL,
ETDE8 VARCHAR(11) NULL,
LETDE8 VARCHAR(11) NULL,
LETEE9 VARCHAR(11) NULL,
ETEE9 VARCHAR(11) NULL,
ETEI9 VARCHAR(11) NULL,
LETEI9 VARCHAR(11) NULL,
LETDI9 VARCHAR(11) NULL,
ETDI9 VARCHAR(11) NULL,
ETDE9 VARCHAR(11) NULL,
LETDE9 VARCHAR(11) NULL,
LETEE10 VARCHAR(11) NULL,
ETEE10 VARCHAR(11) NULL,
ETEI10 VARCHAR(11) NULL,
LETEI10 VARCHAR(11) NULL,
LETDI10 VARCHAR(11) NULL,
ETDI10 VARCHAR(11) NULL,
ETDE10 VARCHAR(11) NULL,
LETDE10 VARCHAR(11) NULL,
LETEE11 VARCHAR(11) NULL,
ETEE11 VARCHAR(11) NULL,
ETEI11 VARCHAR(11) NULL,
LETEI11 VARCHAR(11) NULL,
LETDI11 VARCHAR(11) NULL,
ETDI11 VARCHAR(11) NULL,
ETDE11 VARCHAR(11) NULL,
LETDE11 VARCHAR(11) NULL,
LETEE12 VARCHAR(11) NULL,
ETEE12 VARCHAR(11) NULL,
ETEI12 VARCHAR(11) NULL,
LETEI12 VARCHAR(11) NULL,
LETDI12 VARCHAR(11) NULL,
ETDI12 VARCHAR(11) NULL,
ETDE12 VARCHAR(11) NULL,
LETDE12 VARCHAR(11) NULL,
ESTEP3 VARCHAR(11) NULL,
ESTEP4 VARCHAR(11) NULL,
LINHA SMALLINT NULL,
NUMVEI VARCHAR(8) NULL,
ULTKMT INT NULL,
PLACA2 VARCHAR(8) NULL,
PLACA3 VARCHAR(8) NULL,
PLACA4 VARCHAR(8) NULL,
QTDPNE SMALLINT NULL)
DECLARE @SWHERE VARCHAR(2000)
SET @SWHERE = ''
IF @PARFRO <> 0 AND @PARVEI <> ''
SET @SWHERE = ' AND  CODFRO = ' + CAST(@PARFRO AS VARCHAR) + ' AND CODVEI = `' + @PARVEI + '`'
ELSE
IF @PARFRO <> 0
SET @SWHERE = ' AND CODFRO = ' + CAST(@PARFRO AS VARCHAR)
ELSE
SET @SWHERE = ' AND CODVEI = `' + @PARVEI + '`'
EXECUTE ('DECLARE CURFRO CURSOR FOR SELECT CODVEI FROM RODVEI WHERE PROPRI in (`S`,`N`)' + @SWHERE)
OPEN CURFRO
DECLARE @CODVEI VARCHAR(8)
DECLARE @STRSQL NVARCHAR(max)
SET @CODVEI = ''
FETCH NEXT FROM CURFRO INTO @CODVEI
WHILE (@@FETCH_STATUS <> -1)
BEGIN
SET @STRSQL = ''
DECLARE CURPPV CURSOR FOR
SELECT PS.POSICA
, ISNULL(PE.CODPNE, '0')
FROM
RODPPV PS
LEFT OUTER JOIN RODPNE PE ON PS.POSICA = PE.POSICA AND @CODVEI = PE.CODVEI AND 'US' = PE.SITUAC
ORDER BY
PS.ORDEM
OPEN CURPPV
DECLARE @STRCAMPOS NVARCHAR(4000)
DECLARE @STRCAMPOSNULO NVARCHAR(4000)
DECLARE @POSICA VARCHAR(8)
DECLARE @CODPNE VARCHAR(11)
DECLARE @I SMALLINT
FETCH NEXT FROM CURPPV INTO @POSICA, @CODPNE
SET @STRCAMPOS = ''
SET @STRCAMPOSNULO = ''
WHILE (@@FETCH_STATUS <> -1)
BEGIN
SET @STRCAMPOSNULO = @STRCAMPOSNULO + 'NULL AS ' + @POSICA + ','
IF @CODPNE = '0'
SET @STRCAMPOS = @STRCAMPOS + 'NULL AS ' + @POSICA + ','
ELSE
SET @STRCAMPOS = @STRCAMPOS + '`' + @CODPNE + '`' + ' AS ' + @POSICA + ','
FETCH NEXT FROM CURPPV INTO @POSICA, @CODPNE
END
DEALLOCATE CURPPV
SET @STRCAMPOS = LEFT(@STRCAMPOS, LEN(@STRCAMPOS) - 1)
SET @STRCAMPOSNULO = LEFT(@STRCAMPOSNULO, LEN(@STRCAMPOSNULO) - 1)
SET @I = 1
WHILE @I <= @NLINHAS
BEGIN
IF @I > 1
SET @STRCAMPOS = @STRCAMPOSNULO
SET @STRSQL = 'INSERT INTO #TEMP_SP_ROD_RELACAO_ESQUEMATICA ' + ' SELECT V.CODVEI,TIPVEI,NUMEIX,V.CODFRO,F.DESCRI AS FROTA,MC.DESCRI AS MARCA,MD.DESCRI AS MODELO,M.NOMMOT AS MOTORISTA, ' + @STRCAMPOS + ',' + CAST(@I AS VARCHAR) + ' AS LINHA,NUMVEI,ULTK
MT,V.PLACA2,V.PLACA3, V.PLACA4, V.QTDPNE ' + 'FROM RODVEI V INNER JOIN RODFRO F ON V.CODFRO = F.CODFRO ' + ' INNER JOIN RODMDV MD ON  V.CODMDV = MD.CODMDV " + " INNER JOIN RODMCV MC ON V.CODMCV = MC.CODMCV ' + ' LEFT OUTER JOIN RODMOT M ON V.CODMOT = M.CO
DMOT' + ' WHERE V.CODVEI = `' + @CODVEI + '`'
SET @I = @I + 1
PRINT @STRSQL;
EXEC SP_EXECUTESQL @STRSQL
END
FETCH NEXT FROM CURFRO INTO @CODVEI
END
SELECT *
FROM
#TEMP_SP_ROD_RELACAO_ESQUEMATICA
DEALLOCATE CURFRO
END