SELECT DISTINCT NFC.CODCON, NFC.CODFIL, NFC.SERCON,
(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'F_%.jpg' AND ANE.CODIGO=NFC.ID_NFC) AS ANEDOC,
(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'CTE_%.jpg' AND ANE.CODIGO=NFC.ID_NFC) AS ANECAN,
(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'A_%.jpg' AND ANE.CODIGO=NFC.ID_NFC) AS ANEASN,
CON.DATCAD
FROM RODNFC AS NFC
INNER JOIN RODANE AS ANE ON NFC.ID_NFC=ANE.CODIGO
INNER JOIN RODCON AS CON ON NFC.CODCON=CON.CODCON AND NFC.CODFIL=CON.CODFIL AND NFC.SERCON=CON.SERCON
WHERE ANE.USUINC='APP' AND
(
	(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'F_%.jpg' AND ANE.CODIGO=NFC.ID_NFC)<>'' OR
	(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'CTE_%.jpg' AND ANE.CODIGO=NFC.ID_NFC)<>'' OR
	(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'A_%.jpg' AND ANE.CODIGO=NFC.ID_NFC)<>''
)


SELECT DISTINCT IOS.CODORD, IOS.FILORD, ORD.SERORD,
(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'F_%.jpg' AND ANE.CODIGO=IOS.ID_IOS) AS ANEDOC,
(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'CTE_%.jpg' AND ANE.CODIGO=IOS.ID_IOS) AS ANECAN,
(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'A_%.jpg' AND ANE.CODIGO=IOS.ID_IOS) AS ANEASN,
ORD.DATCAD
FROM RODIOS AS IOS
INNER JOIN RODANE AS ANE ON IOS.ID_IOS=ANE.CODIGO
INNER JOIN RODORD AS ORD ON IOS.CODORD=ORD.CODIGO AND IOS.FILORD=ORD.CODFIL AND IOS.SERORD=ORD.SERORD
WHERE ANE.USUINC='APP' AND
(
	(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'F_%.jpg' AND ANE.CODIGO=IOS.ID_IOS)<>'' OR
	(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'CTE_%.jpg' AND ANE.CODIGO=IOS.ID_IOS)<>'' OR
	(SELECT TOP 1 ANE.CANEXO FROM RODANE AS ANE WHERE ANE.CANEXO LIKE 'A_%.jpg' AND ANE.CODIGO=IOS.ID_IOS)<>''
)

SELECT * FROM RODANE WHERE USUINC='APP'