--CREATE VIEW VW_ALL_CTRC_OST_NF AS
SELECT CON.CODPAG, PAG.RAZSOC AS PAGADOR, CON.CODFIL, CON.SERCON AS SERIE, CON.CODCON AS CODIGO, CON.DATCAD,
CON.SITUAC, CON.CODREM, REM.RAZSOC AS REMETENTE, CON.CODDES, DEST.RAZSOC AS DESTINATARIO, 'CTRC' AS TIPDOC
FROM RODCON CON
INNER JOIN RODCLI PAG ON CON.CODPAG=PAG.CODCLIFOR
LEFT OUTER JOIN RODCLI REM ON CON.CODREM=REM.CODCLIFOR
LEFT OUTER JOIN RODCLI DEST ON CON.CODDES=DEST.CODCLIFOR
WHERE CON.SITUAC NOT IN ('C', 'I') AND CON.TIPCON<>'L'

UNION ALL

SELECT ORD.CODPAG, PAG.RAZSOC AS PAGADOR, ORD.CODFIL, ORD.SERORD AS SERIE, ORD.CODIGO, ORD.DATCAD,
ORD.SITUAC, ORD.CODREM, REM.RAZSOC AS REMETENTE, ORD.CODDES, DEST.RAZSOC AS DESTINATARIO, 'OST' AS TIPDOC
FROM RODORD ORD
INNER JOIN RODCLI PAG ON ORD.CODPAG=PAG.CODCLIFOR
LEFT OUTER JOIN RODCLI REM ON ORD.CODREM=REM.CODCLIFOR
LEFT OUTER JOIN RODCLI DEST ON ORD.CODDES=DEST.CODCLIFOR
WHERE ORD.SITUAC NOT IN ('C', 'I') AND ORD.TIPORD<>'L'

UNION ALL

SELECT ENT.CODCLIFOR AS CODPAG, PAG.RAZSOC AS PAGADOR, ENT.CODFIL, ENT.SERSUB AS SERIE, ENT.CODIGO, NULL AS DATCAD,
ENT.SITUAC, NULL AS CODREM, NULL AS REMETENTE, NULL AS CODDES, NULL AS DESTINATARIO, 'NF' AS TIPDOC
FROM ESTNOT ENT
INNER JOIN RODCLI PAG ON ENT.CODCLIFOR=PAG.CODCLIFOR
WHERE ENT.SERSUB NOT IN ('1', '2') AND ENT.SITUAC NOT IN ('C', 'I')