--CREATE VIEW VW_CTRC_OST_X_MAN_SEM_OCO_FINALIZADORA AS
SELECT COM.*, NFC.NOTFIS, NFC.SERIEN, NFC.VLRMER, NFC.VMERSE, NFC.PESOKG
FROM VW_CTRC_OST_X_MAN COM
LEFT OUTER JOIN RODNFC NFC ON COM.CODIGO=NFC.CODCON AND COM.SERIE=NFC.SERCON AND COM.FILIAL=NFC.CODFIL
WHERE TIPDOC='C' AND
DOCKEY NOT IN (
	SELECT COM.DOCKEY
	FROM VW_CTRC_OST_X_MAN COM
	LEFT OUTER JOIN RODNFC NFC ON COM.CODIGO=NFC.CODCON AND COM.SERIE=NFC.SERCON AND COM.FILIAL=NFC.CODFIL
	LEFT OUTER JOIN RODOCH OCH ON NFC.ID_NFC=OCH.ID_NFC
	WHERE COM.TIPDOC='C' AND OCH.CODOCO IN (1, 138)
)

UNION ALL

SELECT COM.*, IOS.NOTFIS, IOS.SERIEN, IOS.VLRMER, IOS.VMERSE, IOS.PESOKG
FROM VW_CTRC_OST_X_MAN COM
LEFT OUTER JOIN RODIOS IOS ON COM.CODIGO=IOS.CODORD AND COM.SERIE=IOS.SERORD AND COM.FILIAL=IOS.FILORD
WHERE TIPDOC='O' AND
DOCKEY NOT IN (
	SELECT COM.DOCKEY
	FROM VW_CTRC_OST_X_MAN COM
	LEFT OUTER JOIN RODIOS IOS ON COM.CODIGO=IOS.CODORD AND COM.SERIE=IOS.SERORD AND COM.FILIAL=IOS.FILORD
	LEFT OUTER JOIN RODOCH OCH ON IOS.ID_IOS=OCH.ID_IOS
	WHERE COM.TIPDOC='O' AND OCH.CODOCO IN (1, 138)
)