--CREATE VIEW VW_CON_NFC_SEM_FINALIZADOR AS
SELECT 'CTE' AS TIPDOC, CON.CODCON AS CODIGO, CON.SERCON AS SERIE, CON.CODFIL, NFC.ID_NFC AS ID_NFC_IOS,
NFC.NOTFIS, NFC.SERIEN, MOT.CODMOT, MOT.NOMMOT, MOT.NUMCPF, CON.PLACA, CON.PLACA2, CON.DATEMI,
REM.RAZSOC AS REMETENTE, MREM.DESCRI AS MUNREM, MREM.ESTADO AS ESTREM, DEST.RAZSOC AS DESTINATARIO,
MDES.DESCRI AS MUNDES, MDES.ESTADO AS ESTDES
FROM RODCON CON
LEFT OUTER JOIN RODNFC NFC ON CON.CODCON=NFC.CODCON AND CON.SERCON = NFC.SERCON AND CON.CODFIL = NFC.CODFIL
LEFT OUTER JOIN RODMOT MOT ON CON.CODMOT=MOT.CODMOT
LEFT OUTER JOIN RODCLI REM ON CON.CODREM=REM.CODCLIFOR
LEFT OUTER JOIN RODCLI DEST ON CON.CODDES=DEST.CODCLIFOR
LEFT OUTER JOIN RODMUN MREM ON REM.CODMUN=MREM.CODMUN
LEFT OUTER JOIN RODMUN MDES ON DEST.CODMUN=MDES.CODMUN
WHERE CON.DATEMI>='2023-01-01' AND CON.SITUAC<>'C' AND CON.CODMAN IS NOT NULL AND
NFC.ID_NFC NOT IN (
	SELECT NFC.ID_NFC
	FROM RODCON CON
	LEFT OUTER JOIN RODNFC NFC ON CON.CODCON=NFC.CODCON AND CON.SERCON=NFC.SERCON AND CON.CODFIL=NFC.CODFIL
	LEFT OUTER JOIN RODOCH OCH ON NFC.ID_NFC=OCH.ID_NFC
	WHERE OCH.CODOCO IN (1, 138)
)

UNION ALL

SELECT 'OST' AS TIPDOC, ORD.CODIGO, ORD.SERORD AS SERIE, ORD.CODFIL, IOS.ID_IOS AS ID_NFC_IOS, IOS.NOTFIS,
IOS.SERIEN, MOT.CODMOT, MOT.NOMMOT, MOT.NUMCPF, ORD.PLACA, ORD.PLACA2, ORD.DATEMI, REM.RAZSOC AS REMETENTE,
MREM.DESCRI AS MUNREM, MREM.ESTADO AS ESTREM, DEST.RAZSOC AS DESTINATARIO, MDES.DESCRI AS MUNDES, MDES.ESTADO AS ESTDES
FROM RODORD ORD
LEFT OUTER JOIN RODIOS IOS ON ORD.CODIGO=IOS.CODORD AND ORD.SERORD=IOS.SERORD AND ORD.CODFIL=IOS.FILORD
LEFT OUTER JOIN RODMOT MOT ON ORD.CODMOT=MOT.CODMOT
LEFT OUTER JOIN RODCLI REM ON ORD.CODREM=REM.CODCLIFOR
LEFT OUTER JOIN RODCLI DEST ON ORD.CODDES=DEST.CODCLIFOR
LEFT OUTER JOIN RODMUN MREM ON REM.CODMUN=MREM.CODMUN
LEFT OUTER JOIN RODMUN MDES ON DEST.CODMUN=MDES.CODMUN
WHERE ORD.DATEMI>='2023-01-01' AND ORD.SITUAC<>'C' AND ORD.CODMAN IS NOT NULL AND
IOS.ID_IOS NOT IN (
	SELECT IOS.ID_IOS
	FROM RODORD ORD
	LEFT OUTER JOIN RODIOS IOS ON ORD.CODIGO=IOS.CODORD AND ORD.SERORD=IOS.SERORD AND ORD.CODFIL=IOS.FILORD
	LEFT OUTER JOIN RODOCH OCH ON IOS.ID_IOS=OCH.ID_IOS
	WHERE OCH.CODOCO IN (1, 138)
)