--CREATE VIEW VW_CTRC_OST_X_MAN AS
SELECT CONCAT(CODIGO, '-', SERIE, '-', FILIAL) AS DOCKEY, CODIGO, SERIE, FILIAL, SITUAC, CODPAG, DATINC, CODMAN, SERMAN, FILMAN, DATEMI, TIPMAN, PLACA2, CODLIN, TIPDOC
FROM (
	SELECT CON.CODCON AS 'CODIGO', CON.SERCON AS 'SERIE', CON.CODFIL AS 'FILIAL', CON.SITUAC, CON.CODPAG, CON.DATINC,
	MAN.CODMAN, MAN.SERMAN, MAN.CODFIL AS 'FILMAN', MAN.DATEMI, MAN.TIPMAN, MAN.PLACA2, MAN.CODLIN, IMA.TIPDOC,
	ROW_NUMBER() OVER (PARTITION BY CON.CODCON, CON.SERCON, CON.CODFIL ORDER BY MAN.DATEMI DESC) AS DATA_ORDER
	FROM RODCON CON
	LEFT OUTER JOIN RODIMA IMA ON CON.CODCON=IMA.CODDOC AND CON.SERCON=IMA.SERDOC AND CON.CODFIL=IMA.FILDOC AND IMA.TIPDOC='C'
	LEFT OUTER JOIN RODMAN MAN ON IMA.CODMAN=MAN.CODMAN AND IMA.SERMAN=MAN.SERMAN AND IMA.FILMAN=MAN.CODFIL
) DOC
WHERE DATA_ORDER<=1 AND CODMAN IS NOT NULL AND SITUAC<>'C'

UNION ALL

SELECT CONCAT(CODIGO, '-', SERIE, '-', FILIAL) AS DOCKEY, CODIGO, SERIE, FILIAL, SITUAC, CODPAG, DATINC, CODMAN, SERMAN, FILMAN, DATEMI, TIPMAN, PLACA2, CODLIN, TIPDOC
FROM (
	SELECT ORD.CODIGO, ORD.SERORD AS 'SERIE', ORD.CODFIL AS 'FILIAL', ORD.SITUAC, ORD.CODPAG, ORD.DATINC,
	MAN.CODMAN, MAN.SERMAN, MAN.CODFIL AS 'FILMAN', MAN.DATEMI, MAN.TIPMAN, MAN.PLACA2, MAN.CODLIN, IMA.TIPDOC,
	ROW_NUMBER() OVER (PARTITION BY ORD.CODIGO, ORD.SERORD, ORD.CODFIL ORDER BY MAN.DATEMI DESC) AS DATA_ORDER
	FROM RODORD ORD
	LEFT OUTER JOIN RODIMA IMA ON ORD.CODIGO=IMA.CODDOC AND ORD.SERORD=IMA.SERDOC AND ORD.CODFIL=IMA.FILDOC AND IMA.TIPDOC='O'
	LEFT OUTER JOIN RODMAN MAN ON IMA.CODMAN=MAN.CODMAN AND IMA.SERMAN=MAN.SERMAN AND IMA.FILMAN=MAN.CODFIL
) DOC
WHERE DATA_ORDER<=1 AND CODMAN IS NOT NULL AND SITUAC<>'C'