--CREATE VIEW VW_CONSULTA_ENDERECOS_WMS AS
SELECT IPE.CODFIL, IPE.CODIGO, OSA.CODOSA, CLI.RAZSOC AS 'CLIENTE', PRO.REFERE, IPE.CODPRO,
PRO.DESCRI AS 'PRODUTO', IOL.QUANTI, IOL.NUMVOL,
CASE WHEN IOL.CODAPT IS NULL THEN IOL.CODARE ELSE APT.DESCRI END AS 'ENDEREÇO',
IOL.CODUAM, EMB.DESCRI AS 'EMBALAGEM'
FROM WMSIPE IPE
LEFT OUTER JOIN WMSPRO PRO ON IPE.CODPRO=PRO.CODIGO
LEFT OUTER JOIN WMSOSA OSA ON IPE.CODFIL=OSA.FILPED AND IPE.CODIGO=OSA.CODPED
LEFT OUTER JOIN WMSIOL IOL ON OSA.CODOSA=IOL.CODOSA AND OSA.CODFIL=IOL.FILOSA AND PRO.CODIGO=IOL.CODPRO
LEFT OUTER JOIN WMSAPT APT ON IOL.CODAPT=APT.CODAPT
LEFT OUTER JOIN RODCLI CLI ON OSA.CODCLIFOR=CLI.CODCLIFOR
LEFT OUTER JOIN WMSEMB EMB ON IOL.CODEMB=EMB.CODEMB
WHERE OSA.CODCTS=147