--CREATE VIEW VW_DETALHE_EVENTO AS
SELECT ACE.ID_ACE, ACE.VLRUNI, ACE.QUANTI, ACE.SITUAC, CLIV.RAZSOC AS 'RAZSOC_VEI', CCT.TIPDOC, CCTA.TIPDOC AS 'TIPDOC_ALL', CCTA.CODCON AS 'CODIGO_CCT', CCTA.SERCON AS 'SERIE_CCT', CCTA.CODFIL AS 'FILIAL_CCT', VPA.SOMA_PESCAL AS 'SOMA_PESCAL_ALL',
CLIA.FISJUR AS 'FISJUR_ALL', CLIA.CODCGC AS 'CODCGC_ALL', CLIA.CODCPF AS 'CODCPF_ALL', CLIA.RAZSOC AS 'RAZSOC_ALL', FIL.CODEMP, CON.CODCON, CON.SERCON, CON.CODFIL AS 'FILCON', CON.DATCAD AS 'DATCAD_CON', VPC.SOMA_PESCAL AS 'SOMA_PESCAL_CON',
CLIPC.CODCLIFOR AS 'CODCLIFOR_PAG_CON', CLIPC.FISJUR AS 'FISJUR_PAG_CON', CLIPC.CODCGC AS 'CODCGC_PAG_CON', CLIPC.CODCPF AS 'CODCPF_PAG_CON', CLIPC.RAZSOC AS 'RAZSOC_PAG_CON', ORD.CODIGO AS 'CODORD', ORD.SERORD, ORD.CODFIL AS 'FILORD', ORD.DATCAD AS 'DATCAD_ORD',
EST.CODIGO AS 'CODNOT', EST.SERSUB AS 'SERNOT', EST.CODFIL AS 'FILNOT', EST.DATEMI AS 'DATEMI_NOT', CLIPN.CODCLIFOR AS 'CODCLIFOR_PAG_NOT', CLIPN.FISJUR AS 'FISJUR_PAG_NOT', CLIPN.CODCGC AS 'CODCGC_PAG_NOT', CLIPN.CODCPF AS 'CODCPF_PAG_NOT', CLIPN.RAZSOC AS 'RAZSOC_PAG_NOT',
VPO.SOMA_PESCAL AS 'SOMA_PESCAL_ORD', CLIPO.CODCLIFOR AS 'CODCLIFOR_PAG_ORD', CLIPO.FISJUR AS 'FISJUR_PAG_ORD', CLIPO.CODCGC AS 'CODCGC_PAG_ORD', CLIPO.CODCPF AS 'CODCPF_PAG_ORD', CLIPO.RAZSOC AS 'RAZSOC_PAG_ORD'
FROM RODACE ACE
LEFT OUTER JOIN RODVEI VEI ON ACE.CODVEI=VEI.CODVEI
LEFT OUTER JOIN RODCLI CLIV ON VEI.CODPRO=CLIV.CODCLIFOR
LEFT OUTER JOIN RODCCT CCT ON ACE.ID_ACE=CCT.ID_ACE
LEFT OUTER JOIN RODCCT CCTA ON ACE.ID_ACE=CCTA.ID_ACE
LEFT OUTER JOIN VW_CTRC_OST_NF_SS VPA ON CCTA.CODCON=VPA.CODCON AND CCTA.SERCON=VPA.SERCON AND CCTA.CODFIL=VPA.CODFIL
LEFT OUTER JOIN RODCLI CLIA ON VPA.CODPAG=CLIA.CODCLIFOR
LEFT OUTER JOIN RODFIL FIL ON CCT.CODFIL=FIL.CODFIL
LEFT OUTER JOIN RODCON CON ON CCT.CODCON=CON.CODCON AND CCT.SERCON=CON.SERCON AND CCT.CODFIL=CON.CODFIL
LEFT OUTER JOIN VW_CTRC_OST_NF_SS VPC ON CON.CODCON=VPC.CODCON AND CON.SERCON=VPC.SERCON AND CON.CODFIL=VPC.CODFIL
LEFT OUTER JOIN RODCLI CLIPC ON CON.CODPAG=CLIPC.CODCLIFOR
LEFT OUTER JOIN RODORD ORD ON CCT.CODCON=ORD.CODIGO AND CCT.SERCON=ORD.SERORD AND CCT.CODFIL=ORD.CODFIL
LEFT OUTER JOIN RODORN ORN ON ORD.CODIGO=ORN.CODORD AND ORD.SERORD=ORN.SERORD AND ORD.CODFIL=ORN.FILORD
LEFT OUTER JOIN ESTNOT EST ON ORN.CODNOT=EST.CODIGO AND ORN.SERNOT=EST.SERSUB AND ORN.FILNOT=EST.CODFIL
LEFT OUTER JOIN RODCLI CLIPN ON EST.CODCLIFOR=CLIPN.CODCLIFOR
LEFT OUTER JOIN VW_CTRC_OST_NF_SS VPO ON ORD.CODIGO=VPO.CODCON AND ORD.SERORD=VPO.SERCON AND ORD.CODFIL=VPO.CODFIL
LEFT OUTER JOIN RODCLI CLIPO ON ORD.CODPAG=CLIPO.CODCLIFOR