--CREATE VIEW VW_DOC_X_MAN_RMC AS
SELECT DISTINCT MAN.FILIAL, MAN.SERIE, MAN.CODIGO, MAN.SITUAC, MAN.DATINC, MAN.TIPDOC, MAN.TIPMAN,
CMO.CODCMO, CMO.DESCRI AS 'TABELA DE FRETE', MAN.FILMAN, MAN.SERMAN, MAN.CODMAN, MAN.DATEMI, MAN.PLACA2 AS 'PLACA2_MAN',
CAR.CODFIL_RMC, CAR.CODRMC, CAR.DATREF, CAR.PLACA2 AS 'PLACA2_RMC', NFC.NOTFIS, NFC.SERIEN, NFC.PESOKG, NFC.VLRMER, NFC.VMERSE
FROM VW_ULTIMO_MANIFESTO_CAMPINAS MAN --USAR A VIEW "VW_ULTIMO_MANIFESTO_X_DOC" PARA TODAS AS FILIAIS
LEFT OUTER JOIN RODNFC NFC ON MAN.FILIAL=NFC.CODFIL AND MAN.SERIE=NFC.SERCON AND MAN.CODIGO=NFC.CODCON AND MAN.TIPDOC='C'
LEFT OUTER JOIN RODCON CON ON MAN.FILIAL=CON.CODFIL AND MAN.SERIE=CON.SERCON AND MAN.CODIGO=CON.CODCON AND MAN.TIPDOC='C'
LEFT OUTER JOIN VW_ULTIMO_ROMANEIO_CARGA_CAMPINAS CAR --USAR A VIEW "VW_ULTIMO_ROMANEIO_CARGA" PARA TODAS AS FILIAIS
	ON CON.CODFIL=CAR.FILIAL AND CON.SERCON=CAR.SERIE AND CON.CODCON=CAR.CODIGO AND CAR.TIPDOC='C'
LEFT OUTER JOIN RODFRA FRA ON MAN.TABPAD=FRA.CODFRE
LEFT OUTER JOIN RODCMO CMO ON FRA.CODCMO=CMO.CODCMO
WHERE MAN.TIPDOC='C'

UNION ALL

SELECT DISTINCT MAN.FILIAL, MAN.SERIE, MAN.CODIGO, MAN.SITUAC, MAN.DATINC, MAN.TIPDOC, MAN.TIPMAN,
CMO.CODCMO, CMO.DESCRI AS 'TABELA DE FRETE', MAN.FILMAN, MAN.SERMAN, MAN.CODMAN, MAN.DATEMI, MAN.PLACA2 AS 'PLACA2_MAN',
CAR.CODFIL_RMC, CAR.CODRMC, CAR.DATREF, CAR.PLACA2 AS 'PLACA2_RMC', IOS.NOTFIS, IOS.SERIEN, IOS.PESOKG, IOS.VLRMER, IOS.VMERSE
FROM VW_ULTIMO_MANIFESTO_CAMPINAS MAN --USAR A VIEW "VW_ULTIMO_MANIFESTO_X_DOC" PARA TODAS AS FILIAIS
LEFT OUTER JOIN RODIOS IOS ON MAN.FILIAL=IOS.FILORD AND MAN.SERIE=IOS.SERORD AND MAN.CODIGO=IOS.CODORD AND MAN.TIPDOC='O'
LEFT OUTER JOIN RODORD ORD ON MAN.FILIAL=ORD.CODFIL AND MAN.SERIE=ORD.SERORD AND MAN.CODIGO=ORD.CODIGO AND MAN.TIPDOC='O'
LEFT OUTER JOIN VW_ULTIMO_ROMANEIO_CARGA_CAMPINAS CAR --USAR A VIEW "VW_ULTIMO_ROMANEIO_CARGA" PARA TODAS AS FILIAIS
	ON ORD.CODFIL=CAR.FILIAL AND ORD.SERORD=CAR.SERIE AND ORD.CODIGO=CAR.CODIGO AND CAR.TIPDOC='O'
LEFT OUTER JOIN RODFRA FRA ON MAN.TABPAD=FRA.CODFRE
LEFT OUTER JOIN RODCMO CMO ON FRA.CODCMO=CMO.CODCMO
WHERE MAN.TIPDOC='O'