--CREATE VIEW VW_DOC_X_MANIFESTO AS
SELECT CON.CODFIL AS FILIAL, CON.SERCON AS SERIE, CON.CODCON AS CODIGO, CON.DATINC, CON.USUATU, CON.SITUAC,
NFC.NOTFIS, NFC.SERIEN, CON.CODPAG, CLI.RAZSOC, CMO.CODCMO, CMO.DESCRI AS 'TABELA DE FRETE',
MAN.TIPMAN, MAN.CODFIL AS FILMAN, MAN.SERMAN, MAN.CODMAN, 'CTRC' AS TIPDOC
FROM RODCON CON
INNER JOIN RODCLI CLI ON CON.CODPAG=CLI.CODCLIFOR
INNER JOIN RODNFC NFC ON CON.CODFIL=NFC.CODFIL AND CON.SERCON=NFC.SERCON AND CON.CODCON=NFC.CODCON
INNER JOIN RODIMA IMA ON CON.CODFIL=IMA.FILDOC AND CON.SERCON=IMA.SERDOC AND CON.CODCON=IMA.CODDOC
LEFT OUTER JOIN RODMAN MAN ON IMA.FILMAN=MAN.CODFIL AND IMA.SERMAN=MAN.SERMAN AND IMA.CODMAN=MAN.CODMAN
LEFT OUTER JOIN RODFRA FRA ON CON.TABPAD=FRA.CODFRE
LEFT OUTER JOIN RODCMO CMO ON FRA.CODCMO=CMO.CODCMO
WHERE (MAN.TIPMAN<>7 OR MAN.TIPMAN IS NULL) AND CON.DATINC>='2021-01-01'

UNION ALL

SELECT ORD.CODFIL AS FILIAL, ORD.SERORD AS SERIE, ORD.CODIGO, ORD.DATINC, ORD.USUATU, ORD.SITUAC,
IOS.NOTFIS, IOS.SERIEN, ORD.CODPAG, CLI.RAZSOC, CMO.CODCMO, CMO.DESCRI AS 'TABELA DE FRETE',
MAN.TIPMAN, MAN.CODFIL AS FILMAN, MAN.SERMAN, MAN.CODMAN, 'OST' AS TIPDOC
FROM RODORD ORD
INNER JOIN RODCLI CLI ON ORD.CODPAG=CLI.CODCLIFOR
INNER JOIN RODIOS IOS ON ORD.CODFIL=IOS.FILORD AND ORD.SERORD=IOS.SERORD AND ORD.CODIGO=IOS.CODORD
INNER JOIN RODIMA IMA ON ORD.CODFIL=IMA.FILDOC AND ORD.SERORD=IMA.SERDOC AND ORD.CODIGO=IMA.CODDOC
LEFT OUTER JOIN RODMAN MAN ON IMA.FILMAN=MAN.CODFIL AND IMA.SERMAN=MAN.SERMAN AND IMA.CODMAN=MAN.CODMAN
LEFT OUTER JOIN RODFRA FRA ON ORD.TABPAD=FRA.CODFRE
LEFT OUTER JOIN RODCMO CMO ON FRA.CODCMO=CMO.CODCMO
WHERE (MAN.TIPMAN<>7 OR MAN.TIPMAN IS NULL) AND ORD.DATINC>='2021-01-01'