SELECT DISTINCT CON.CODCON, CON.SERCON, CON.CODFIL, OCH.CODOCO
FROM VW_SS_CTRC_OST_NF VCON
LEFT OUTER JOIN RODCON CON ON VCON.CODCON=CON.CODCON AND VCON.SERCON=CON.SERCON AND VCON.CODFIL=CON.CODFIL
LEFT OUTER JOIN RODNFC NFC ON CON.CODCON=NFC.CODCON AND CON.SERCON=NFC.SERCON AND CON.CODFIL=NFC.CODFIL
LEFT OUTER JOIN RODOCH OCH ON NFC.ID_NFC=OCH.ID_NFC
WHERE VCON.TIPO='CTRC' AND
CAST(CON.CODFIL AS VARCHAR) + '-' + CON.SERCON + '-' + CAST(CON.CODCON AS VARCHAR) IN (
	SELECT CAST(CON.CODFIL AS VARCHAR) + '-' + CON.SERCON + '-' + CAST(CON.CODCON AS VARCHAR) AS DOCKEY
	FROM VW_SS_CTRC_OST_NF VCON
	LEFT OUTER JOIN RODCON CON ON VCON.CODCON=CON.CODCON AND VCON.SERCON=CON.SERCON AND VCON.CODFIL=CON.CODFIL
	LEFT OUTER JOIN RODNFC NFC ON CON.CODCON=NFC.CODCON AND CON.SERCON=NFC.SERCON AND CON.CODFIL=NFC.CODFIL
	LEFT OUTER JOIN RODOCH OCH ON NFC.ID_NFC=OCH.ID_NFC
	WHERE VCON.TIPO='CTRC' AND OCH.CODOCO IN (112)
)