--CREATE VIEW VW_PESO_EVENTO_SEM_SSONIC AS
SELECT ACE.ID_ACE,
(
	SELECT SUM(VDRP.SOMA_PESCAL)
	FROM VW_SS_DOCS_RENTABILIDADE VDRP
	LEFT OUTER JOIN RODCCT CCTP ON VDRP.CODCON=CCTP.CODCON AND VDRP.SERCON=CCTP.SERCON AND VDRP.CODFIL=CCTP.CODFIL
	LEFT OUTER JOIN RODACE ACEP ON CCTP.ID_ACE=ACEP.ID_ACE
	LEFT OUTER JOIN RODCLI CLI ON VDRP.CODPAG=CLI.CODCLIFOR
	WHERE ACEP.ID_ACE=ACE.ID_ACE AND (REPLACE(LEFT(CLI.CODCGC, 10), '.', '') <> '47705660' OR CLI.CODCGC IS NULL)
) AS TOTAL_PESCAL
FROM RODACE ACE
WHERE ACE.SITUAC NOT IN ('I', 'C')