--CREATE VIEW VW_PONTUACAO_MOTORISTAS AS
SELECT *,
(
	SELECT SUM(MTV.PONTOS)
	FROM RODMOT MOT
	LEFT OUTER JOIN RODCAM CAM ON MOT.CODMOT=CAM.CODMOT
	LEFT OUTER JOIN RODMTV MTV ON CAM.CODMTV=MTV.CODMTV
	WHERE MOT.CODMOT=CFR.CODMOT AND MTV.CODMTV=10
) AS 'TOTAL_PENALIDADES',
(
	SELECT COUNT(CAM.CODCAM)
	FROM RODMOT MOT
	LEFT OUTER JOIN RODCAM CAM ON MOT.CODMOT=CAM.CODMOT
	--LEFT OUTER JOIN RODMTV MTV ON CAM.CODMTV=MTV.CODMTV
	WHERE MOT.CODMOT=CFR.CODMOT AND CAM.CODMTV=11
) AS 'TOTAL_PREMIOS'
FROM (
	SELECT DISTINCT MOT.CODMOT, MOT.NOMMOT, CFR.CODIGO AS 'CODCFR', CFR.SERSUB, CFR.CODFIL AS 'FILCFR', CFR.SITUAC AS 'SITUAC_CFR',
	MAN.CODMAN, MAN.SERMAN, MAN.CODFIL AS 'FILMAN', MAN.DATEMI AS 'DATEMI_MAN', PCR.SOMA_PESMAN, PCR.SOMA_PESCFR, LIN.KMTPLA,
	INI.ESTADO AS 'ESTADO_INI', FIM.ESTADO AS 'ESTADO_FIM',
	ROW_NUMBER() OVER (PARTITION BY CFR.CODIGO, CFR.SERSUB, CFR.CODFIL ORDER BY LIN.KMTPLA DESC) AS DATA_ORDER
	FROM RODMOT MOT
	LEFT OUTER JOIN RODCFR CFR ON MOT.CODMOT=CFR.CODMOT
	LEFT OUTER JOIN VW_SS_PESO_CONTRATOS PCR ON CFR.CODFIL=PCR.CODFIL_CFR AND CFR.SERSUB=PCR.SERSUB AND CFR.CODIGO=PCR.CODIGO_CFR
	LEFT OUTER JOIN RODMAN MAN ON PCR.CODMAN=MAN.CODMAN AND PCR.FILMAN=MAN.CODFIL AND PCR.SERMAN=MAN.SERMAN
	LEFT OUTER JOIN RODLIN LIN ON MAN.CODLIN=LIN.CODLIN
	LEFT OUTER JOIN RODMUN INI ON LIN.PONINI=INI.CODITN
	LEFT OUTER JOIN RODMUN FIM ON LIN.PONFIM=FIM.CODITN
	WHERE CFR.SITUAC<>'C' AND INI.ESTADO<>FIM.ESTADO AND MAN.DATEMI>'2022-03-01' AND MOT.SITUAC<>'I'
) CFR 
WHERE DATA_ORDER<=1 AND CFR.CODMOT=1748