--CREATE VIEW VW_RODIMA_RENTABILIDADE AS
SELECT IMA.CODDOC, IMA.SERDOC, IMA.FILDOC, VSPC.CODMAN, VSPC.SERMAN, VSPC.CODFIL AS 'FILMAN', VSPC.PESCAL, VSPC.SOMA_PESCAL, CFR.CODIGO, CFR.SERSUB, CFR.CODFIL AS 'FILCFR',
CFR.VLRFRE, CFR.VLRPED, CFR.SITUAC AS 'SITUAC_CFR', CFR.OUTDEB, CFR.OUTCRE, MAN.PLACA2, MAN.DATEMI, MAN.CUSMAN, MAN.SITUAC AS 'SITUAC_MAN', MAN.TIPMAN,
MAN.CUSPED, LIN.KMTPLA, VEI.PROPRI
FROM RODIMA IMA
LEFT OUTER JOIN VW_MAN_SOMAPESCAL_SEM_SSONIC VSPC ON IMA.CODMAN=VSPC.CODMAN AND IMA.SERMAN=VSPC.SERMAN AND IMA.FILMAN=VSPC.CODFIL
			AND IMA.CODDOC=VSPC.CODDOC AND IMA.SERDOC=VSPC.SERDOC AND IMA.FILDOC=VSPC.FILDOC
LEFT OUTER JOIN RODMAN MAN ON VSPC.CODMAN=MAN.CODMAN AND VSPC.SERMAN=MAN.SERMAN AND VSPC.CODFIL=MAN.CODFIL
LEFT OUTER JOIN RODLIN LIN ON MAN.CODLIN=LIN.CODLIN
LEFT OUTER JOIN RODVEI VEI ON MAN.PLACA=VEI.CODVEI
LEFT OUTER JOIN VW_RODDCO DCO ON VSPC.CODMAN=DCO.CODMAN AND VSPC.SERMAN=DCO.SERMAN AND VSPC.CODFIL=DCO.FILMAN
LEFT OUTER JOIN RODCFR CFR ON DCO.CODIGO=CFR.CODIGO AND DCO.SERSUB=CFR.SERSUB AND DCO.CODFIL=CFR.CODFIL