--CREATE VIEW VW_RODORN_DETALHE_CTR_REPOM AS
SELECT ORN.CODNOT, ORN.SERNOT, ORN.FILNOT, VNS.SOMA_PESCAL AS 'SOMA_PESCAL_NOT', ORDN.CODIGO AS 'CODORD_NOT', ORDN.SERORD AS 'SERORD_NOT',
ORDN.CODFIL AS 'FILORD_NOT', VMPN.CODMAN AS 'CODMAN_NOT', VMPN.SERMAN AS 'SERMAN_NOT', VMPN.CODFIL AS 'FILMAN_NOT',
VMPN.SOMA_PESCAL AS 'SOMA_PESCAL_MAN_NOT', CFRN.CODIGO AS 'CODIGO_CFR_NOT', CFRN.SERSUB AS 'SERSUB_CFR_NOT', CFRN.CODFIL AS 'CODFIL_CFR_NOT',
CFRN.VLRFRE AS 'VLRFRE_NOT', CFRN.VLRPED AS 'VLRPED_NOT', CFRN.OUTDEB AS 'OUTDEB_NOT', CFRN.OUTCRE AS 'OUTCRE_NOT', MANN.TIPMAN AS 'TIPMAN_NOT'
FROM RODORN ORN
LEFT OUTER JOIN VW_CTRC_OST_NF_SS VNS ON ORN.CODORD=VNS.CODCON AND ORN.SERORD=VNS.SERCON AND ORN.FILORD=VNS.CODFIL
LEFT OUTER JOIN RODORD ORDN ON ORN.CODORD=ORDN.CODIGO AND ORN.SERORD=ORDN.SERORD AND ORN.FILORD=ORDN.CODFIL
LEFT OUTER JOIN RODIMA IMANT ON ORDN.CODIGO=IMANT.CODDOC AND ORDN.SERORD=IMANT.SERDOC AND ORDN.CODFIL=IMANT.FILDOC
LEFT OUTER JOIN VW_MAN_SOMAPESCAL_SEM_SSONIC VMPN ON IMANT.CODMAN=VMPN.CODMAN AND IMANT.SERMAN=VMPN.SERMAN AND IMANT.FILMAN=VMPN.CODFIL AND IMANT.CODDOC=VMPN.CODDOC AND IMANT.SERDOC=VMPN.SERDOC AND IMANT.FILDOC=VMPN.FILDOC
LEFT OUTER JOIN VW_RODDCO DCON ON VMPN.CODMAN=DCON.CODMAN AND VMPN.SERMAN=DCON.SERMAN AND VMPN.CODFIL=DCON.FILMAN
LEFT OUTER JOIN RODCFR CFRN ON DCON.CODIGO=CFRN.CODIGO AND DCON.SERSUB=CFRN.SERSUB AND DCON.CODFIL=CFRN.CODFIL
LEFT OUTER JOIN RODMAN MANN ON VMPN.CODMAN=MANN.CODMAN AND VMPN.SERMAN=MANN.SERMAN AND VMPN.CODFIL=MANN.CODFIL
LEFT OUTER JOIN RODLIN LINMN ON MANN.CODLIN=LINMN.CODLIN