--CREATE VIEW VW_RODORN_RENTABILIDADE AS
SELECT VCON.CODCON AS 'CODORD', VCON.SERCON AS 'SERORD', VCON.CODFIL AS 'FILORD', VCON.SOMA_PESOKG,
(SELECT (SUM(IOS.PESCAL)) FROM RODIOS IOS WHERE ORD.CODIGO=IOS.CODORD AND ORD.SERORD=IOS.SERORD AND ORD.CODFIL=IOS.FILORD) AS SOMA_PESCAL,
VCON.SOMA_VLRMER, ORN.CODNOT, ORN.SERNOT, ORN.FILNOT, SEG.CODSEG, SEG.PERSEG
FROM RODORN ORN
LEFT OUTER JOIN VW_CTRC_OST_NF_SS VCON ON ORN.CODORD=VCON.CODCON AND ORN.SERORD=VCON.SERCON AND ORN.FILORD=VCON.CODFIL
LEFT OUTER JOIN RODORD ORD ON VCON.CODCON=ORD.CODIGO AND VCON.SERCON=ORD.SERORD AND VCON.CODFIL=ORD.CODFIL
LEFT OUTER JOIN RODSEG SEG ON ORD.CODSEG=SEG.CODSEG
LEFT OUTER JOIN RODFRA FRA ON ORD.TABPAD=FRA.CODFRE