--CREATE VIEW VW_RODCCT_SUM_PESO_EVENTO AS
SELECT CCT.ID_ACE, CCT.TIPDOC, CON.CODCON, CON.SERCON, CON.CODFIL AS 'FILCON',
(SELECT SUM(SOMA_PESCAL_CON) FROM (SELECT SUM(NFC.PESOKG) AS 'SOMA_PESCAL_CON' FROM RODNFC NFC LEFT OUTER JOIN RODCON C ON NFC.CODCON=C.CODCON AND NFC.SERCON=C.SERCON AND NFC.CODFIL=C.CODFIL LEFT OUTER JOIN RODCCT CT ON NFC.CODCON=CT.CODCON AND NFC.SERCON=CT.SERCON AND NFC.CODFIL=CT.CODFIL LEFT OUTER JOIN RODACE AC ON CT.ID_ACE=AC.ID_ACE WHERE AC.ID_ACE=ACE.ID_ACE AND C.CODCON=CON.CODCON AND C.SERCON=CON.SERCON AND C.CODFIL=CON.CODFIL) AS SPC) AS PESO_EVENTO_CON,
CCLI.FISJUR AS 'FISJUR_CON', CCLI.CODCGC AS 'CODCGC_CON', CCLI.CODCPF AS 'CODCPF_CON', CCLI.RAZSOC AS 'RAZSOC_CON', ORD.CODIGO AS 'CODORD',
ORD.SERORD, ORD.CODFIL AS 'FILORD',
(SELECT SUM(SOMA_PESCAL_ORD) FROM (SELECT SUM(IOS.PESCAL) AS 'SOMA_PESCAL_ORD' FROM RODIOS IOS LEFT OUTER JOIN RODORD O ON IOS.CODORD=O.CODIGO AND IOS.SERORD=O.SERORD AND IOS.FILORD=O.CODFIL LEFT OUTER JOIN RODCCT CT ON O.CODIGO=CT.CODCON AND O.SERORD=CT.SERCON AND O.CODFIL=CT.CODFIL LEFT OUTER JOIN RODACE AC ON CT.ID_ACE=AC.ID_ACE WHERE AC.ID_ACE=ACE.ID_ACE AND O.CODIGO=ORD.CODIGO AND O.SERORD=ORD.SERORD AND O.CODFIL=ORD.CODFIL) AS SPC) AS PESO_EVENTO_ORD,
OCLI.FISJUR AS 'FISJUR_ORD', OCLI.CODCGC AS 'CODCGC_ORD', OCLI.CODCPF AS 'CODCPF_ORD', OCLI.RAZSOC AS 'RAZSOC_ORD', ACE.SITUAC,
(SELECT SUM(SOMA_PESCAL_CON) FROM (SELECT SUM(NFC.PESCAL) AS 'SOMA_PESCAL_CON' FROM RODNFC NFC LEFT OUTER JOIN RODCON C ON NFC.CODCON=C.CODCON AND NFC.SERCON=C.SERCON AND NFC.CODFIL=C.CODFIL LEFT OUTER JOIN RODCCT CT ON C.CODCON=CT.CODCON AND C.SERCON=CT.SERCON AND C.CODFIL=CT.CODFIL LEFT OUTER JOIN RODACE AC ON CT.ID_ACE=AC.ID_ACE WHERE AC.ID_ACE=ACE.ID_ACE) AS SPC) AS SOMA_PESO_EVENTO_CON,
(SELECT SUM(SOMA_PESCAL_ORD) FROM (SELECT SUM(IOS.PESCAL) AS 'SOMA_PESCAL_ORD' FROM RODIOS IOS LEFT OUTER JOIN RODORD O ON IOS.CODORD=O.CODIGO AND IOS.SERORD=O.SERORD AND IOS.FILORD=O.CODFIL LEFT OUTER JOIN RODCCT CT ON O.CODIGO=CT.CODCON AND O.SERORD=CT.SERCON AND O.CODFIL=CT.CODFIL LEFT OUTER JOIN RODACE AC ON CT.ID_ACE=AC.ID_ACE WHERE AC.ID_ACE=ACE.ID_ACE) AS SPC) AS SOMA_PESO_EVENTO_ORD
FROM RODCCT CCT
LEFT OUTER JOIN RODCON CON ON CCT.CODCON=CON.CODCON AND CCT.SERCON=CON.SERCON AND CCT.CODFIL=CON.CODFIL
LEFT OUTER JOIN RODCLI CCLI ON CON.CODPAG=CCLI.CODCLIFOR
LEFT OUTER JOIN RODORD ORD ON CCT.CODCON=ORD.CODIGO AND CCT.SERCON=ORD.SERORD AND CCT.CODFIL=ORD.CODFIL
LEFT OUTER JOIN RODCLI OCLI ON ORD.CODPAG=OCLI.CODCLIFOR
LEFT OUTER JOIN RODACE ACE ON CCT.ID_ACE=ACE.ID_ACE
WHERE CCT.TIPDOC IN ('C', 'O') AND ACE.SITUAC <> 'C'