--CREATE VIEW VW_RODIMA_DETALHE_CTR_REPOM AS
SELECT IMACO.CODDOC AS 'CODDOC_IMACO', IMACO.SERDOC AS 'SERDOC_IMACO', IMACO.FILDOC AS 'FILDOC_IMACO', VMP.CODMAN, VMP.SERMAN,
VMP.CODFIL AS 'FILMAN', VMP.SOMA_PESCAL AS 'SOMA_PESCAL_MAN', CFR.CODIGO AS 'CODIGO_CFR', CFR.SERSUB AS 'SERSUB_CFR',
CFR.CODFIL AS 'CODFIL_CFR', CFR.VLRFRE, CFR.SITUAC AS 'SITUAC_CFR', CFR.VLRPED, CFR.OUTDEB, CFR.OUTCRE, MAN.SITUAC AS 'SITUAC_MAN', MAN.TIPMAN
FROM RODIMA IMACO
LEFT OUTER JOIN VW_MAN_SOMAPESCAL_SEM_SSONIC VMP ON IMACO.CODMAN=VMP.CODMAN AND IMACO.SERMAN=VMP.SERMAN AND IMACO.FILMAN=VMP.CODFIL AND IMACO.CODDOC=VMP.CODDOC AND IMACO.SERDOC=VMP.SERDOC AND IMACO.FILDOC=VMP.FILDOC
LEFT OUTER JOIN VW_RODDCO DCO ON VMP.CODMAN=DCO.CODMAN AND VMP.SERMAN=DCO.SERMAN AND VMP.CODFIL=DCO.FILMAN
LEFT OUTER JOIN RODCFR CFR ON DCO.CODIGO=CFR.CODIGO AND DCO.SERSUB=CFR.SERSUB AND DCO.CODFIL=CFR.CODFIL
LEFT OUTER JOIN RODMAN MAN ON VMP.CODMAN=MAN.CODMAN AND VMP.SERMAN=MAN.SERMAN AND VMP.CODFIL=MAN.CODFIL
LEFT OUTER JOIN RODLIN LINM ON MAN.CODLIN=LINM.CODLIN