--CREATE VIEW VW_RODORN_MAN_RENTABILIDADE AS
SELECT ORN.CODNOT, ORN.SERNOT, ORN.FILNOT, ORD.CODIGO, ORD.SERORD, ORD.CODFIL, VSPC.CODMAN, VSPC.SERMAN, VSPC.CODFIL AS 'FILMAN', VSPC.PESCAL, VSPC.SOMA_PESCAL,
MAN.PLACA2, MAN.DATEMI, MAN.CUSMAN, MAN.TIPMAN, MAN.CUSPED, VEI.PROPRI, LIN.KMTPLA, CFR.CODIGO AS 'CODCFR', CFR.SERSUB, CFR.CODFIL AS 'FILCFR',
CFR.VLRFRE, CFR.VLRPED, CFR.OUTDEB, CFR.OUTCRE, CCT.ID_ACE, ACE.VLRUNI, ACE.QUANTI, ACE.SITUAC, ECLI.CODCLIFOR, ECLI.RAZSOC
FROM RODORN ORN
LEFT OUTER JOIN RODORD ORD ON ORN.CODORD=ORD.CODIGO AND ORN.SERORD=ORD.SERORD AND ORN.FILORD=ORD.CODFIL
LEFT OUTER JOIN RODIMA IMA ON ORD.CODIGO=IMA.CODDOC AND ORD.SERORD=IMA.SERDOC AND ORD.CODFIL=IMA.FILDOC
LEFT OUTER JOIN VW_MAN_SOMAPESCAL_SEM_SSONIC VSPC ON IMA.CODMAN=VSPC.CODMAN AND IMA.SERMAN=VSPC.SERMAN AND IMA.FILMAN=VSPC.CODFIL
			AND IMA.CODDOC=VSPC.CODDOC AND IMA.SERDOC=VSPC.SERDOC AND IMA.FILDOC=VSPC.FILDOC
LEFT OUTER JOIN RODMAN MAN ON VSPC.CODMAN=MAN.CODMAN AND VSPC.SERMAN=MAN.SERMAN AND VSPC.CODFIL=MAN.CODFIL
LEFT OUTER JOIN RODVEI VEI ON MAN.PLACA=VEI.CODVEI
LEFT OUTER JOIN RODLIN LIN ON MAN.CODLIN=LIN.CODLIN
LEFT OUTER JOIN VW_RODDCO DCO ON VSPC.CODMAN=DCO.CODMAN AND VSPC.SERMAN=DCO.SERMAN AND VSPC.CODFIL=DCO.FILMAN
LEFT OUTER JOIN RODCFR CFR ON DCO.CODIGO=CFR.CODIGO AND DCO.SERSUB=CFR.SERSUB AND DCO.CODFIL=CFR.CODFIL
LEFT OUTER JOIN RODCCT CCT ON ORD.CODIGO=CCT.CODCON AND ORD.SERORD=CCT.SERCON AND ORD.CODFIL=CCT.CODFIL
LEFT OUTER JOIN RODACE ACE ON CCT.ID_ACE=ACE.ID_ACE
LEFT OUTER JOIN RODVEI EVEI ON ACE.CODVEI=EVEI.CODVEI
LEFT OUTER JOIN RODCLI ECLI ON EVEI.CODPRO=ECLI.CODCLIFOR