--CONSULTA BANDAS (ENTRADA)
--CREATE VIEW VW_RECEBIMENTO_BRIDGESTONE AS
SELECT TAB.*, SUBSTRING(ARQTXT,77,13) AS M41, CAST(DATINC AS date) AS DTM41, DATINC AS DTM41_TIME,
CASE
	WHEN TAB.SITUAC='D' AND TAB.TOTAL_CONFE IS NULL AND NUMNFC IS NULL THEN 'EM TRÂNSITO'
	WHEN TAB.SITUAC='D' AND TAB.TOTAL_CONFE IS NULL THEN 'AGUARDANDO CONFERÊNCIA'
	WHEN TAB.SITUAC='D' AND TAB.TOTAL_CONFE IS NOT NULL THEN 'EM CONFERÊNCIA'
	WHEN TAB.SITUAC='N' AND SUBSTRING(ARQTXT,77,13) IS NULL AND TAB.SITOSA='I' THEN 'CONFERÊNCIA FINALIZADA'
	WHEN TAB.SITUAC='N' AND SUBSTRING(ARQTXT,77,13) IS NULL AND TAB.SITOSA='D' THEN 'CONSOLIDADO'
	WHEN TAB.SITUAC='N' AND SUBSTRING(ARQTXT,77,13) IS NOT NULL THEN 'M41 ENVIADO'
END AS 'STATUS',
CASE
	WHEN TAB.SITUAC='D' AND TAB.TOTAL_CONFE IS NULL AND NUMNFC IS NULL THEN 1
	WHEN TAB.SITUAC='D' AND TAB.TOTAL_CONFE IS NULL THEN 2
	WHEN TAB.SITUAC='D' AND TAB.TOTAL_CONFE IS NOT NULL THEN 3
	WHEN TAB.SITUAC='N' AND SUBSTRING(ARQTXT,77,13) IS NULL AND TAB.SITOSA='I' THEN 4
	WHEN TAB.SITUAC='N' AND SUBSTRING(ARQTXT,77,13) IS NULL AND TAB.SITOSA='D' THEN 5
	WHEN TAB.SITUAC='N' AND SUBSTRING(ARQTXT,77,13) IS NOT NULL THEN 6
END AS 'STATUS_ORDER'
FROM (
	SELECT PED.*, CAST(TTC.TOTAL AS int) AS TOTAL_CONFE
	FROM (
		SELECT SUBSTRING(PED.OBSERV,30,13) AS ARQUIVO, PED.CODIGO AS PEDIDO, CAST(TOTAL AS int) AS TOTAL_PROD,
		MDA.CODIGO AS DOCUMENTAL, ENF.CODENF AS FISICA, OSA.CODOSA, 'M40' AS TIPO, SUBSTRING(MDA.NUMDOC, PATINDEX('%[^0]%', MDA.NUMDOC), 10) AS NUMDOC, PED.SITUAC, OSA.SITUAC AS SITOSA,
		CAST(PED.DATPED AS date) AS DATPED, PED.DATPED AS DATPED_TIME, DMR.NUMDOC AS NUMNFC
		FROM (
			SELECT CODFIL, CODIGO, SUM(QUANTI) AS TOTAL
			FROM WMSIPE
			GROUP BY CODFIL, CODIGO
		) AS TTL
		LEFT OUTER JOIN WMSPED PED ON TTL.CODFIL=PED.CODFIL AND TTL.CODIGO=PED.CODIGO
		LEFT OUTER JOIN WMSMDP MDP ON TTL.CODFIL=MDP.FILPED AND TTL.CODIGO=MDP.CODPED
		LEFT OUTER JOIN WMSMDA MDA ON MDA.CODFIL=MDP.FILMDA AND MDA.CODIGO=MDP.CODMDA
		LEFT OUTER JOIN WMSENF ENF ON ENF.FILPED=PED.CODFIL AND ENF.CODPED=PED.CODIGO
		LEFT OUTER JOIN WMSOSA OSA ON ENF.CODFIL=OSA.FILENF AND ENF.CODENF=OSA.CODENF
		LEFT OUTER JOIN (
			SELECT RDMR.NUMDOC FROM RODDMR RDMR
			LEFT OUTER JOIN RODMRE MRE ON RDMR.CODMRE=MRE.CODIGO
			WHERE MRE.TIPMOV='E' AND MRE.CODFIL=10 AND MRE.CODMVI=3
		) AS DMR ON SUBSTRING(MDA.NUMDOC, PATINDEX('%[^0]%', MDA.NUMDOC), 10)=DMR.NUMDOC		
		WHERE DATPED >='2022-08-04' AND PED.CODCTS = '153' AND PED.TIPPED = 'E' AND PED.SITUAC <> 'C' AND
		MDA.NUMDOC IS NOT NULL AND MDA.NUMDOC <> '123'
	) AS PED
	LEFT OUTER JOIN (
		SELECT FILDOC, CODDOC, SUM(QUANTI) AS TOTAL
		FROM HISUAM
		GROUP BY FILDOC, CODDOC
	) AS TTC ON PED.FISICA=TTC.CODDOC
) AS TAB
LEFT OUTER JOIN (
	SELECT FILDOC, CODDOC, ARQTXT, TIPARQ, DATINC
	FROM LOG_INTEGRACAO_TXT
	WHERE TIPARQ = 'WMS03' AND ARQTXT IS NOT NULL
) AS ARC ON TAB.FISICA=ARC.CODDOC
ORDER BY TAB.PEDIDO