--CREATE VIEW VW_SS_DOCS_RENTCFR AS
SELECT DISTINCT VDR.*, CFR.CODIGO AS 'CODCFR', CFR.SERSUB AS 'SERCFR', CFR.CODFIL AS 'FILCFR', CFR.VLRFRE, CFR.VLRPED, VPC.SOMA_PESCFR,
MAN.TIPMAN
FROM VW_SS_DOCS_RENTABILIDADE VDR
LEFT OUTER JOIN RODIMA IMA ON VDR.CODCON=IMA.CODDOC AND VDR.SERCON=IMA.SERDOC AND VDR.CODFIL=IMA.FILDOC
LEFT OUTER JOIN RODMAN MAN ON IMA.CODMAN=MAN.CODMAN AND IMA.SERMAN=MAN.SERMAN AND IMA.FILMAN=MAN.CODFIL
LEFT OUTER JOIN VW_RODDCO DCO ON IMA.CODMAN=DCO.CODMAN AND IMA.SERMAN=DCO.SERMAN AND IMA.FILMAN=DCO.FILMAN
LEFT OUTER JOIN RODCFR CFR ON DCO.CODIGO=CFR.CODIGO AND DCO.SERSUB=CFR.SERSUB AND DCO.CODFIL=CFR.CODFIL
LEFT OUTER JOIN VW_SS_PESO_CONTRATOS VPC ON CFR.CODIGO=VPC.CODIGO_CFR AND CFR.SERSUB=VPC.SERSUB AND CFR.CODFIL=VPC.CODFIL_CFR
WHERE MAN.SITUAC NOT IN ('I', 'C') AND CFR.SITUAC NOT IN ('I', 'C') AND CFR.NUMVIA IS NOT NULL AND CFR.SITCIO IS NOT NULL AND CFR.SITCIO<>'C'