--CREATE VIEW VW_SS_PESO_CONTRATOS AS
SELECT DISTINCT CON.CODFIL, CON.SERCON AS 'SERIE', CON.CODCON AS 'CODIGO', CON.CODPAG, CON.DATCAD,
CON.SITUAC, CON.TIPCON AS 'TIPO', CON.TOTFRE, IMA.FILMAN, IMA.SERMAN, IMA.CODMAN,
CFR.CODIGO AS 'CODIGO_CFR', CFR.SERSUB, CFR.CODFIL AS 'CODFIL_CFR',
(
	SELECT SUM (PESCAL)
	FROM RODNFC NFS
	WHERE NFS.CODCON=CON.CODCON AND NFS.SERCON=CON.SERCON AND NFS.CODFIL=CON.CODFIL
) AS SOMA_PESCAL,
(
	SELECT SUM (NFM.PESCAL)
	FROM RODIMA IMM
	LEFT OUTER JOIN RODNFC NFM ON IMM.FILDOC=NFM.CODFIL AND IMM.SERDOC=NFM.SERCON AND IMM.CODDOC=NFM.CODCON
	WHERE IMM.FILMAN=IMA.FILMAN AND IMM.SERMAN=IMA.SERMAN AND IMM.CODMAN=IMA.CODMAN
) AS SOMA_PESMAN,
CASE WHEN CFR.CODIGO IS NULL THEN NULL ELSE
(
	SELECT SUM (NFF.PESCAL)
	FROM RODIMA IMF
	LEFT OUTER JOIN RODCON CN ON CN.CODFIL=IMF.FILDOC AND CN.SERCON=IMF.SERDOC AND CN.CODCON=IMF.CODDOC
	LEFT OUTER JOIN RODNFC NFF ON IMF.FILDOC=NFF.CODFIL AND IMF.SERDOC=NFF.SERCON AND IMF.CODDOC=NFF.CODCON
	LEFT OUTER JOIN VW_RODDCO DCO ON DCO.FILMAN=IMF.FILMAN AND DCO.SERMAN=IMF.SERMAN AND DCO.CODMAN=IMF.CODMAN 
	LEFT OUTER JOIN RODCFR CR ON DCO.CODIGO=CR.CODIGO AND DCO.SERSUB=CR.SERSUB AND DCO.CODFIL=CR.CODFIL
	LEFT OUTER JOIN RODCLI CL ON CN.CODPAG=CL.CODCLIFOR
	WHERE CR.CODIGO=CFR.CODIGO AND CR.SERSUB=CFR.SERSUB AND CR.CODFIL=CFR.CODFIL AND REPLACE(LEFT(CL.CODCGC, 10), '.', '') <> '47705660'
) END AS SOMA_PESCFR
FROM RODCON CON
LEFT OUTER JOIN RODIMA IMA ON CON.CODFIL=IMA.FILDOC AND CON.SERCON=IMA.SERDOC AND CON.CODCON=IMA.CODDOC
LEFT OUTER JOIN RODDCO DCO ON DCO.FILMAN=IMA.FILMAN AND DCO.SERMAN=IMA.SERMAN AND DCO.CODMAN=IMA.CODMAN
LEFT OUTER JOIN RODCFR CFR ON DCO.CODIGO=CFR.CODIGO AND DCO.SERSUB=CFR.SERSUB AND DCO.CODFIL=CFR.CODFIL

UNION ALL

SELECT DISTINCT ORD.CODFIL, ORD.SERORD AS 'SERIE', ORD.CODIGO, ORD.CODPAG, ORD.DATCAD,
ORD.SITUAC, ORD.TIPORD AS 'TIPO', ORD.TOTFRE, IMA.FILMAN, IMA.SERMAN, IMA.CODMAN,
CFR.CODIGO AS ' CODIGO_CFR', CFR.SERSUB, CFR.CODFIL AS 'CODFIL_CFR',
(
	SELECT SUM (PESCAL)
	FROM RODIOS IOS
	WHERE IOS.CODORD=ORD.CODIGO AND IOS.SERORD=ORD.SERORD AND IOS.FILORD=ORD.CODFIL
) AS SOMA_PESCAL,
(
	SELECT SUM (IOM.PESCAL)
	FROM RODIMA IMM
	LEFT OUTER JOIN RODIOS IOM ON IMM.FILDOC=IOM.FILORD AND IMM.SERDOC=IOM.SERORD AND IMM.CODDOC=IOM.CODORD
	WHERE IMM.FILMAN=IMA.FILMAN AND IMM.SERMAN=IMA.SERMAN AND IMM.CODMAN=IMA.CODMAN
) AS SOMA_PESMAN,
CASE WHEN CFR.CODIGO IS NULL THEN NULL ELSE 
(
	SELECT SUM (IOF.PESOKG)
	FROM RODIMA IMF
	LEFT OUTER JOIN RODORD OD ON IMF.FILDOC=OD.CODFIL AND IMF.SERDOC=OD.SERORD AND IMF.CODDOC=OD.CODIGO
	LEFT OUTER JOIN RODIOS IOF ON IMF.FILDOC=IOF.FILORD AND IMF.SERDOC=IOF.SERORD AND IMF.CODDOC=IOF.CODORD
	LEFT OUTER JOIN VW_RODDCO DCO ON DCO.FILMAN=IMF.FILMAN AND DCO.SERMAN=IMF.SERMAN AND DCO.CODMAN=IMF.CODMAN 
	LEFT OUTER JOIN RODCFR CR ON DCO.CODIGO=CR.CODIGO AND DCO.SERSUB=CR.SERSUB AND DCO.CODFIL=CR.CODFIL
	LEFT OUTER JOIN RODCLI CL ON OD.CODPAG=CL.CODCLIFOR
	WHERE CR.CODIGO=CFR.CODIGO AND CR.SERSUB=CFR.SERSUB AND CR.CODFIL=CFR.CODFIL AND REPLACE(LEFT(CL.CODCGC, 10), '.', '') <> '47705660'
) END AS SOMA_PESCFR
FROM RODORD ORD
LEFT OUTER JOIN RODIMA IMA ON ORD.CODFIL=IMA.FILDOC AND ORD.SERORD=IMA.SERDOC AND ORD.CODIGO=IMA.CODDOC
LEFT OUTER JOIN RODDCO DCO ON DCO.FILMAN=IMA.FILMAN AND DCO.SERMAN=IMA.SERMAN AND DCO.CODMAN=IMA.CODMAN
LEFT OUTER JOIN RODCFR CFR ON DCO.CODIGO=CFR.CODIGO AND DCO.SERSUB=CFR.SERSUB AND DCO.CODFIL=CFR.CODFIL