--CREATE VIEW VW_SS_DOCS_RENTABILIDADE_ORIGEM AS
SELECT 
CASE WHEN VDN.TIPO IS NOT NULL THEN VDN.TIPO ELSE VDS.TIPO END AS TIPO,
CASE WHEN VDN.CODCON IS NOT NULL THEN VDN.CODCON ELSE VDS.CODCON END AS CODCON,
CASE WHEN VDN.SERCON IS NOT NULL THEN VDN.SERCON ELSE VDS.SERCON END AS SERCON,
CASE WHEN VDN.CODFIL IS NOT NULL THEN VDN.CODFIL ELSE VDS.CODFIL END AS CODFIL,
CASE WHEN VDN.TIPO_DOC IS NOT NULL THEN VDN.TIPO_DOC ELSE VDS.TIPO_DOC END AS TIPO_DOC,
CASE WHEN VDN.SITUAC IS NOT NULL THEN VDN.SITUAC ELSE VDS.SITUAC END AS SITUAC,
CASE WHEN VDN.SOMA_PESCAL IS NOT NULL THEN VDN.SOMA_PESCAL ELSE VDS.SOMA_PESCAL END AS SOMA_PESCAL,
CASE WHEN VDN.SOMA_VLRMER IS NOT NULL THEN VDN.SOMA_VLRMER ELSE VDS.SOMA_VLRMER END AS SOMA_VLRMER,
CASE WHEN VDN.CODPAG IS NOT NULL THEN VDN.CODPAG ELSE VDS.CODPAG END AS CODPAG,
CASE WHEN VDN.CODLIN IS NOT NULL THEN VDN.CODLIN ELSE VDS.CODLIN END AS CODLIN,
CASE WHEN VDN.TABPAD IS NOT NULL THEN VDN.TABPAD ELSE VDS.TABPAD END AS TABPAD,
CASE WHEN VDN.CODSEG IS NOT NULL THEN VDN.CODSEG ELSE VDS.CODSEG END AS CODSEG,
CASE WHEN VDN.ICMVLR IS NOT NULL THEN VDN.ICMVLR ELSE VDS.ICMVLR END AS ICMVLR,
VDS.TOTFRE, FIL.CODEMP, VDS.TIPO AS 'TIPO_ORIGEM', VDS.DATCAD,
VDS.CODCON AS 'CODCON_ORIGEM', VDS.SERCON AS 'SERCON_ORIGEM', VDS.CODFIL AS 'CODFIL_ORIGEM'
FROM VW_CTRC_OST_NF_SS VDS
LEFT OUTER JOIN RODORN ORN ON VDS.CODNOT=ORN.CODNOT AND VDS.SERNOT=ORN.SERNOT AND VDS.FILNOT=ORN.FILNOT
LEFT OUTER JOIN VW_CTRC_OST_NF_SS VDN ON ORN.CODORD=VDN.CODCON AND ORN.SERORD=VDN.SERCON AND ORN.FILORD=VDN.CODFIL
LEFT OUTER JOIN RODFIL FIL ON VDS.CODFIL=FIL.CODFIL