--CREATE VIEW VW_SS_DOCS_RENTEVENTOS AS
SELECT DISTINCT VDR.*, ACE.ID_ACE, EVE.DESCRI, CLI.CODCLIFOR, CLI.RAZSOC, ACE.QUANTI, ACE.VLRUNI, VPE.TOTAL_PESCAL
FROM VW_SS_DOCS_RENTABILIDADE VDR
LEFT OUTER JOIN RODCCT CCT ON VDR.CODCON=CCT.CODCON AND VDR.SERCON=CCT.SERCON AND VDR.CODFIL=CCT.CODFIL
LEFT OUTER JOIN RODACE ACE ON CCT.ID_ACE=ACE.ID_ACE
LEFT OUTER JOIN RODVEI VEI ON ACE.CODVEI=VEI.CODVEI
LEFT OUTER JOIN RODCLI CLI ON VEI.CODPRO=CLI.CODCLIFOR
LEFT OUTER JOIN VW_PESO_EVENTO_SEM_SSONIC VPE ON ACE.ID_ACE=VPE.ID_ACE
LEFT OUTER JOIN RODEVE EVE ON ACE.CODEVE=EVE.CODEVE
WHERE ACE.SITUAC NOT IN ('I', 'C')