--CREATE VIEW VW_ULTIMA_MOV_PORT AS
SELECT *
FROM (
	SELECT VEI.CODVEI, MPO.TIPMOV, POR.CODPOR, POR.DESCRI AS PORTARIA, MPO.DATENT, MPO.DATSAI, POR.CODFIL AS 'FIL.PORT', MPO.OBSER1, MPO.OBSER2,
	ROW_NUMBER() OVER (PARTITION BY VEI.CODVEI ORDER BY MPO.DATATU DESC) AS DATA_ORDER
	FROM RODVEI VEI
	INNER JOIN RODMPO MPO ON VEI.CODVEI=MPO.PLACA
	LEFT OUTER JOIN RODPOR POR ON MPO.CODPOR=POR.CODPOR
) DOCS
WHERE DATA_ORDER<=1
ORDER BY CODVEI