--CREATE VIEW VW_ULTIMO_MANIFESTO_X_ENTRADA_VEICULO_CAMP AS
SELECT *
FROM (
	SELECT UEP.PLACA, MAN.CODMAN, MAN.SERMAN, MAN.CODFIL, MAN.DATEMI,
	ROW_NUMBER() OVER (PARTITION BY UEP.PLACA ORDER BY MAN.DATEMI DESC) AS DATA_ORDER
	FROM VW_ULTIMA_ENTRADA_PORTARIA_CAMP UEP
	INNER JOIN RODMAN MAN ON UEP.PLACA=MAN.PLACA2
	WHERE MAN.SITUAC<>'C'
) DOC
WHERE DATA_ORDER<=1