--CREATE VIEW VW_ULTIMO_ROMANEIO_CARGA AS
SELECT DISTINCT CON.CODFIL AS FILIAL, CON.SERCON AS SERIE, CON.CODCON AS CODIGO, CON.SITUAC,
(SELECT TOP 1 RMC.CODRMC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=10 ORDER BY RMC.DATREF DESC) AS CODRMC,
(SELECT TOP 1 RMC.CODFIL FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=10 ORDER BY RMC.DATREF DESC) AS CODFIL_RMC,
(SELECT TOP 1 RMC.SITUAC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=10 ORDER BY RMC.DATREF DESC) AS SITUAC_RMC,
(SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=10 ORDER BY RMC.DATREF DESC) AS DATREF,
IRC.NOTFIS, IRC.TIPDOC
FROM RODCON CON
INNER JOIN RODIRC IRC ON CON.CODFIL=IRC.FILDOC AND CON.SERCON=IRC.SERDOC AND CON.CODCON=IRC.CODDOC
WHERE IRC.TIPDOC='C' AND IRC.FILRMC=10
AND (SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON ORDER BY RMC.DATREF DESC) >= '2021-01-01'

UNION ALL

SELECT DISTINCT CON.CODFIL AS FILIAL, CON.SERCON AS SERIE, CON.CODCON AS CODIGO, CON.SITUAC,
(SELECT TOP 1 RMC.CODRMC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=5 ORDER BY RMC.DATREF DESC) AS CODRMC,
(SELECT TOP 1 RMC.CODFIL FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=5 ORDER BY RMC.DATREF DESC) AS CODFIL_RMC,
(SELECT TOP 1 RMC.SITUAC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=5 ORDER BY RMC.DATREF DESC) AS SITUAC_RMC,
(SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=5 ORDER BY RMC.DATREF DESC) AS DATREF,
IRC.NOTFIS, IRC.TIPDOC
FROM RODCON CON
INNER JOIN RODIRC IRC ON CON.CODFIL=IRC.FILDOC AND CON.SERCON=IRC.SERDOC AND CON.CODCON=IRC.CODDOC
WHERE IRC.TIPDOC='C' AND IRC.FILRMC=5
AND (SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON ORDER BY RMC.DATREF DESC) >= '2021-01-01'

UNION ALL

SELECT DISTINCT CON.CODFIL AS FILIAL, CON.SERCON AS SERIE, CON.CODCON AS CODIGO, CON.SITUAC,
(SELECT TOP 1 RMC.CODRMC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=11 ORDER BY RMC.DATREF DESC) AS CODRMC,
(SELECT TOP 1 RMC.CODFIL FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=11 ORDER BY RMC.DATREF DESC) AS CODFIL_RMC,
(SELECT TOP 1 RMC.SITUAC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=11 ORDER BY RMC.DATREF DESC) AS SITUAC_RMC,
(SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON AND RMC.CODFIL=11 ORDER BY RMC.DATREF DESC) AS DATREF,
IRC.NOTFIS, IRC.TIPDOC
FROM RODCON CON
INNER JOIN RODIRC IRC ON CON.CODFIL=IRC.FILDOC AND CON.SERCON=IRC.SERDOC AND CON.CODCON=IRC.CODDOC
WHERE IRC.TIPDOC='C' AND IRC.FILRMC=11
AND (SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=CON.CODFIL AND IRC.SERDOC=CON.SERCON AND IRC.CODDOC=CON.CODCON ORDER BY RMC.DATREF DESC) >= '2021-01-01'

UNION ALL

SELECT DISTINCT ORD.CODFIL AS FILIAL, ORD.SERORD AS SERIE, ORD.CODIGO, ORD.SITUAC,
(SELECT TOP 1 RMC.CODRMC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=10 ORDER BY RMC.DATREF DESC) AS CODRMC,
(SELECT TOP 1 RMC.CODFIL FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=10 ORDER BY RMC.DATREF DESC) AS CODFIL_RMC,
(SELECT TOP 1 RMC.SITUAC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=10 ORDER BY RMC.DATREF DESC) AS SITUAC_RMC,
(SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=10 ORDER BY RMC.DATREF DESC) AS DATREF,
IRC.NOTFIS, IRC.TIPDOC
FROM RODORD ORD
INNER JOIN RODIRC IRC ON ORD.CODFIL=IRC.FILDOC AND ORD.SERORD=IRC.SERDOC AND ORD.CODIGO=IRC.CODDOC
WHERE IRC.TIPDOC='O' AND IRC.FILRMC=10
AND (SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO ORDER BY RMC.DATREF DESC) >= '2021-01-01'

UNION ALL

SELECT DISTINCT ORD.CODFIL AS FILIAL, ORD.SERORD AS SERIE, ORD.CODIGO, ORD.SITUAC,
(SELECT TOP 1 RMC.CODRMC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=5 ORDER BY RMC.DATREF DESC) AS CODRMC,
(SELECT TOP 1 RMC.CODFIL FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=5 ORDER BY RMC.DATREF DESC) AS CODFIL_RMC,
(SELECT TOP 1 RMC.SITUAC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=5 ORDER BY RMC.DATREF DESC) AS SITUAC_RMC,
(SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=5 ORDER BY RMC.DATREF DESC) AS DATREF,
IRC.NOTFIS, IRC.TIPDOC
FROM RODORD ORD
INNER JOIN RODIRC IRC ON ORD.CODFIL=IRC.FILDOC AND ORD.SERORD=IRC.SERDOC AND ORD.CODIGO=IRC.CODDOC
WHERE IRC.TIPDOC='O' AND IRC.FILRMC=5
AND (SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO ORDER BY RMC.DATREF DESC) >= '2021-01-01'

UNION ALL

SELECT DISTINCT ORD.CODFIL AS FILIAL, ORD.SERORD AS SERIE, ORD.CODIGO, ORD.SITUAC,
(SELECT TOP 1 RMC.CODRMC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=11 ORDER BY RMC.DATREF DESC) AS CODRMC,
(SELECT TOP 1 RMC.CODFIL FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=11 ORDER BY RMC.DATREF DESC) AS CODFIL_RMC,
(SELECT TOP 1 RMC.SITUAC FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=11 ORDER BY RMC.DATREF DESC) AS SITUAC_RMC,
(SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO AND RMC.CODFIL=11 ORDER BY RMC.DATREF DESC) AS DATREF,
IRC.NOTFIS, IRC.TIPDOC
FROM RODORD ORD
INNER JOIN RODIRC IRC ON ORD.CODFIL=IRC.FILDOC AND ORD.SERORD=IRC.SERDOC AND ORD.CODIGO=IRC.CODDOC
WHERE IRC.TIPDOC='O' AND IRC.FILRMC=11
AND (SELECT TOP 1 RMC.DATREF FROM RODRMC RMC INNER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC WHERE IRC.FILDOC=ORD.CODFIL AND IRC.SERDOC=ORD.SERORD AND IRC.CODDOC=ORD.CODIGO ORDER BY RMC.DATREF DESC) >= '2021-01-01'