--CREATE VIEW VW_ULTIMO_DOC_X_ENTRADA_VEICULO_CAMP AS
SELECT PLACA, CODMAN, SERMAN, FILMAN, DATEMI_MAN, CODIGO, SERIE, FILIAL, SITUAC, DATINC, TIPDOC
FROM (
	SELECT MVC.PLACA, MVC.CODMAN, MVC.SERMAN, MVC.CODFIL AS 'FILMAN', MVC.DATEMI AS 'DATEMI_MAN',
	CON.CODCON AS 'CODIGO', CON.SERCON AS 'SERIE', CON.CODFIL AS 'FILIAL', CON.SITUAC, CON.DATINC, IMA.TIPDOC,
	ROW_NUMBER() OVER (PARTITION BY MVC.PLACA ORDER BY CON.DATINC DESC) AS DATA_ORDER
	FROM VW_ULTIMO_MANIFESTO_X_ENTRADA_VEICULO_CAMP MVC
	INNER JOIN RODIMA IMA ON MVC.CODMAN=IMA.CODMAN AND MVC.SERMAN=IMA.SERMAN AND MVC.CODFIL=IMA.FILMAN
	LEFT OUTER JOIN RODCON CON ON IMA.CODDOC=CON.CODCON AND IMA.SERDOC=CON.SERCON AND IMA.FILDOC=CON.CODFIL
	WHERE IMA.TIPDOC='C' AND CON.SITUAC<>'C'

	UNION ALL

	SELECT MVC.PLACA, MVC.CODMAN, MVC.SERMAN, MVC.CODFIL AS 'FILMAN', MVC.DATEMI AS 'DATEMI_MAN',
	ORD.CODIGO, ORD.SERORD AS 'SERIE', ORD.CODFIL AS 'FILIAL', ORD.SITUAC, ORD.DATINC, IMA.TIPDOC,
	ROW_NUMBER() OVER (PARTITION BY MVC.PLACA ORDER BY ORD.DATINC DESC) AS DATA_ORDER
	FROM VW_ULTIMO_MANIFESTO_X_ENTRADA_VEICULO_CAMP MVC
	INNER JOIN RODIMA IMA ON MVC.CODMAN=IMA.CODMAN AND MVC.SERMAN=IMA.SERMAN AND MVC.CODFIL=IMA.FILMAN
	LEFT OUTER JOIN RODORD ORD ON IMA.CODDOC=ORD.CODIGO AND IMA.SERDOC=ORD.SERORD AND IMA.FILDOC=ORD.CODFIL
	WHERE IMA.TIPDOC='O' AND ORD.SITUAC<>'C'
) DOC
WHERE DATA_ORDER<=1