--CREATE VIEW VW_ULTIMO_ROMANEIO_DESCARGA AS
SELECT CON.CODFIL AS FILIAL, CON.SERCON AS SERIE, CON.CODCON AS CODIGO, CON.SITUAC,
(SELECT TOP 1 RMD.CODRMD FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=10 ORDER BY RMD.DATREF DESC) AS CODRMD,
(SELECT TOP 1 RMD.CODFIL FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=10 ORDER BY RMD.DATREF DESC) AS CODFIL_RMD,
(SELECT TOP 1 RMD.SITUAC FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=10 ORDER BY RMD.DATREF DESC) AS SITUAC_RMD,
(SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=10 ORDER BY RMD.DATREF DESC) AS DATREF,
IRD.NOTFIS, IRD.TIPDOC, IRD.CODCLIFOR, CLI.RAZSOC, CLI.FISJUR, CLI.CODCGC, CLI.CODCPF, CON.CODSEG, SEG.DESCRI, NFC.ID_NFC AS 'ID NF/IOS', NFC.SERIEN, NFC.VLRMER, NFC.VMERSE
FROM RODCON CON
INNER JOIN RODIRD IRD ON CON.CODFIL=IRD.FILDOC AND CON.SERCON=IRD.SERDOC AND CON.CODCON=IRD.CODDOC
LEFT OUTER JOIN RODCLI CLI ON CON.CODPAG=CLI.CODCLIFOR
LEFT OUTER JOIN RODSEG SEG ON CON.CODSEG=SEG.CODSEG
LEFT OUTER JOIN RODNFC NFC ON IRD.FILDOC=NFC.CODFIL AND IRD.SERDOC=NFC.SERCON AND IRD.CODDOC=NFC.CODCON AND IRD.NOTFIS=NFC.NOTFIS
WHERE IRD.TIPDOC='C' AND IRD.CODFIL=10
AND (SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON ORDER BY RMD.DATREF DESC) >= '2021-01-01'

UNION ALL

SELECT CON.CODFIL AS FILIAL, CON.SERCON AS SERIE, CON.CODCON AS CODIGO, CON.SITUAC,
(SELECT TOP 1 RMD.CODRMD FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=5 ORDER BY RMD.DATREF DESC) AS CODRMD,
(SELECT TOP 1 RMD.CODFIL FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=5 ORDER BY RMD.DATREF DESC) AS CODFIL_RMD,
(SELECT TOP 1 RMD.SITUAC FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=5 ORDER BY RMD.DATREF DESC) AS SITUAC_RMD,
(SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=5 ORDER BY RMD.DATREF DESC) AS DATREF,
IRD.NOTFIS, IRD.TIPDOC, IRD.CODCLIFOR, CLI.RAZSOC, CLI.FISJUR, CLI.CODCGC, CLI.CODCPF, CON.CODSEG, SEG.DESCRI, NFC.ID_NFC AS 'ID NF/IOS', NFC.SERIEN, NFC.VLRMER, NFC.VMERSE
FROM RODCON CON
INNER JOIN RODIRD IRD ON CON.CODFIL=IRD.FILDOC AND CON.SERCON=IRD.SERDOC AND CON.CODCON=IRD.CODDOC
LEFT OUTER JOIN RODCLI CLI ON CON.CODPAG=CLI.CODCLIFOR
LEFT OUTER JOIN RODSEG SEG ON CON.CODSEG=SEG.CODSEG
LEFT OUTER JOIN RODNFC NFC ON IRD.FILDOC=NFC.CODFIL AND IRD.SERDOC=NFC.SERCON AND IRD.CODDOC=NFC.CODCON AND IRD.NOTFIS=NFC.NOTFIS
WHERE IRD.TIPDOC='C' AND IRD.CODFIL=5
AND (SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON ORDER BY RMD.DATREF DESC) >= '2021-01-01'

UNION ALL

SELECT CON.CODFIL AS FILIAL, CON.SERCON AS SERIE, CON.CODCON AS CODIGO, CON.SITUAC,
(SELECT TOP 1 RMD.CODRMD FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=11 ORDER BY RMD.DATREF DESC) AS CODRMD,
(SELECT TOP 1 RMD.CODFIL FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=11 ORDER BY RMD.DATREF DESC) AS CODFIL_RMD,
(SELECT TOP 1 RMD.SITUAC FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=11 ORDER BY RMD.DATREF DESC) AS SITUAC_RMD,
(SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON AND RMD.CODFIL=11 ORDER BY RMD.DATREF DESC) AS DATREF,
IRD.NOTFIS, IRD.TIPDOC, IRD.CODCLIFOR, CLI.RAZSOC, CLI.FISJUR, CLI.CODCGC, CLI.CODCPF, CON.CODSEG, SEG.DESCRI, NFC.ID_NFC AS 'ID NF/IOS', NFC.SERIEN, NFC.VLRMER, NFC.VMERSE
FROM RODCON CON
INNER JOIN RODIRD IRD ON CON.CODFIL=IRD.FILDOC AND CON.SERCON=IRD.SERDOC AND CON.CODCON=IRD.CODDOC
LEFT OUTER JOIN RODCLI CLI ON CON.CODPAG=CLI.CODCLIFOR
LEFT OUTER JOIN RODSEG SEG ON CON.CODSEG=SEG.CODSEG
LEFT OUTER JOIN RODNFC NFC ON IRD.FILDOC=NFC.CODFIL AND IRD.SERDOC=NFC.SERCON AND IRD.CODDOC=NFC.CODCON AND IRD.NOTFIS=NFC.NOTFIS
WHERE IRD.TIPDOC='C' AND IRD.CODFIL=11
AND (SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=CON.CODFIL AND IRD.SERDOC=CON.SERCON AND IRD.CODDOC=CON.CODCON ORDER BY RMD.DATREF DESC) >= '2021-01-01'

UNION ALL

SELECT ORD.CODFIL AS FILIAL, ORD.SERORD AS SERIE, ORD.CODIGO, ORD.SITUAC,
(SELECT TOP 1 RMD.CODRMD FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=10 ORDER BY RMD.DATREF DESC) AS CODRMD,
(SELECT TOP 1 RMD.CODFIL FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=10 ORDER BY RMD.DATREF DESC) AS CODFIL_RMD,
(SELECT TOP 1 RMD.SITUAC FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=10 ORDER BY RMD.DATREF DESC) AS SITUAC_RMD,
(SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=10 ORDER BY RMD.DATREF DESC) AS DATREF,
IRD.NOTFIS, IRD.TIPDOC, IRD.CODCLIFOR, CLI.RAZSOC, CLI.FISJUR, CLI.CODCGC, CLI.CODCPF, ORD.CODSEG, SEG.DESCRI, IOS.ID_IOS AS 'ID NF/IOS', IOS.SERIEN, IOS.VLRMER, IOS.VMERSE
FROM RODORD ORD
INNER JOIN RODIRD IRD ON ORD.CODFIL=IRD.FILDOC AND ORD.SERORD=IRD.SERDOC AND ORD.CODIGO=IRD.CODDOC
LEFT OUTER JOIN RODCLI CLI ON ORD.CODPAG=CLI.CODCLIFOR
LEFT OUTER JOIN RODSEG SEG ON ORD.CODSEG=SEG.CODSEG
LEFT OUTER JOIN RODIOS IOS ON IRD.FILDOC=IOS.FILORD AND IRD.SERDOC=IOS.SERORD AND IRD.CODDOC=IOS.CODORD AND IRD.NOTFIS=IOS.NOTFIS
WHERE IRD.TIPDOC='O' AND IRD.CODFIL=10
AND (SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO ORDER BY RMD.DATREF DESC) >= '2021-01-01'

UNION ALL

SELECT ORD.CODFIL AS FILIAL, ORD.SERORD AS SERIE, ORD.CODIGO, ORD.SITUAC,
(SELECT TOP 1 RMD.CODRMD FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=5 ORDER BY RMD.DATREF DESC) AS CODRMD,
(SELECT TOP 1 RMD.CODFIL FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=5 ORDER BY RMD.DATREF DESC) AS CODFIL_RMD,
(SELECT TOP 1 RMD.SITUAC FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=5 ORDER BY RMD.DATREF DESC) AS SITUAC_RMD,
(SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=5 ORDER BY RMD.DATREF DESC) AS DATREF,
IRD.NOTFIS, IRD.TIPDOC, IRD.CODCLIFOR, CLI.RAZSOC, CLI.FISJUR, CLI.CODCGC, CLI.CODCPF, ORD.CODSEG, SEG.DESCRI, IOS.ID_IOS AS 'ID NF/IOS', IOS.SERIEN, IOS.VLRMER, IOS.VMERSE
FROM RODORD ORD
INNER JOIN RODIRD IRD ON ORD.CODFIL=IRD.FILDOC AND ORD.SERORD=IRD.SERDOC AND ORD.CODIGO=IRD.CODDOC
LEFT OUTER JOIN RODCLI CLI ON ORD.CODPAG=CLI.CODCLIFOR
LEFT OUTER JOIN RODSEG SEG ON ORD.CODSEG=SEG.CODSEG
LEFT OUTER JOIN RODIOS IOS ON IRD.FILDOC=IOS.FILORD AND IRD.SERDOC=IOS.SERORD AND IRD.CODDOC=IOS.CODORD AND IRD.NOTFIS=IOS.NOTFIS
WHERE IRD.TIPDOC='O' AND IRD.CODFIL=5
AND (SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO ORDER BY RMD.DATREF DESC) >= '2021-01-01'

UNION ALL

SELECT ORD.CODFIL AS FILIAL, ORD.SERORD AS SERIE, ORD.CODIGO, ORD.SITUAC,
(SELECT TOP 1 RMD.CODRMD FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=11 ORDER BY RMD.DATREF DESC) AS CODRMD,
(SELECT TOP 1 RMD.CODFIL FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=11 ORDER BY RMD.DATREF DESC) AS CODFIL_RMD,
(SELECT TOP 1 RMD.SITUAC FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=11 ORDER BY RMD.DATREF DESC) AS SITUAC_RMD,
(SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO AND RMD.CODFIL=11 ORDER BY RMD.DATREF DESC) AS DATREF,
IRD.NOTFIS, IRD.TIPDOC, IRD.CODCLIFOR, CLI.RAZSOC, CLI.FISJUR, CLI.CODCGC, CLI.CODCPF, ORD.CODSEG, SEG.DESCRI, IOS.ID_IOS AS 'ID NF/IOS', IOS.SERIEN, IOS.VLRMER, IOS.VMERSE
FROM RODORD ORD
INNER JOIN RODIRD IRD ON ORD.CODFIL=IRD.FILDOC AND ORD.SERORD=IRD.SERDOC AND ORD.CODIGO=IRD.CODDOC
LEFT OUTER JOIN RODCLI CLI ON ORD.CODPAG=CLI.CODCLIFOR
LEFT OUTER JOIN RODSEG SEG ON ORD.CODSEG=SEG.CODSEG
LEFT OUTER JOIN RODIOS IOS ON IRD.FILDOC=IOS.FILORD AND IRD.SERDOC=IOS.SERORD AND IRD.CODDOC=IOS.CODORD AND IRD.NOTFIS=IOS.NOTFIS
WHERE IRD.TIPDOC='O' AND IRD.CODFIL=11
AND (SELECT TOP 1 RMD.DATREF FROM RODRMD RMD INNER JOIN RODIRD IRD ON RMD.CODRMD=IRD.CODRMD AND RMD.CODFIL=IRD.CODFIL WHERE IRD.FILDOC=ORD.CODFIL AND IRD.SERDOC=ORD.SERORD AND IRD.CODDOC=ORD.CODIGO ORDER BY RMD.DATREF DESC) >= '2021-01-01'