--CREATE VIEW VW_VENDA_BRIDGESTONE AS
SELECT ARQUIVO, DATPED, CLIPED, PEDIDO, TTPED, TTATE, MATERIAL, OS, LEITURA, RAZSOC, M51,
DATM51, HRS, AG_BDG, NOTFIS
FROM (
	SELECT ARQUIVO, DATPED, CLIPED, CODFIL, PEDIDO, TTPED, TTATE, MATERIAL, OS,
	CASE
		WHEN M51 IS NULL AND CODOSA IS NULL AND STATUS = 'IMPRESSO' THEN 'SEPARAÇÃO'
		WHEN M51 IS NULL AND CODOSA IS NOT NULL AND STSCNF <> 'C' AND SITOS = 'I'  THEN '2º LEITURA'
		WHEN M51 IS NULL AND STSCNF = 'C' AND SITOS = 'I' THEN '2º LEITURA FINALIZADA'
		WHEN M51 IS NULL AND STSCNF = 'C' AND SITOS = 'D' THEN 'M51 PENDENTE'
		WHEN M51 IS NOT NULL THEN 'M51 ENVIADO'
	ELSE STATUS
	END AS LEITURA,
	RAZSOC, M51, DATM51, HRS, AG_BDG, NOTFIS
	FROM (
		--GERA ARQUIVO M51 (INICIO)
		SELECT DOS.*, SUBSTRING(ARQTXT,77,13) AS M51, CAST(DATINC AS DATETIME) AS DATM51,
		CONVERT(VARCHAR, DATINC, 108) AS HRS
		FROM (
			--SEGUNDA CONFERENCIA(INICIO)
			SELECT DDS.*, IOL.*
			FROM (
				-- QTD ATENDIDA NO PDIDO (FIM)
				SELECT PED.*, 
				CASE
					WHEN MATERIAL='COLA' THEN TTPED
					WHEN TTATE IS NULL THEN 0
				ELSE TTATE
				END AS TTATE
				FROM (
					-- Nº OS - STATUS - CLI - SIT - DATE (INICIO)
					SELECT SUBSTRING(PED.OBSERV,30,17) AS ARQUIVO, PED.CLIPED, PED.CODFIL,
					PED.CODIGO AS PEDIDO, TTPED, TTL.MATERIAL, OSA.CODOSA AS OS,
					CASE 
						WHEN PED.CLIROM IS NOT NULL THEN PED.CLIROM
						WHEN PED.CLIROT IS NULL THEN 'AGUARDANDO'
					ELSE 'SEPARAÇÃO'
					END AS STATUS,
					CLI.RAZSOC, CAST(PED.DATPED AS DATETIME) AS DATPED, PED.SITUAC,
					OSA.SITUAC AS SITOS, OSA.STSCNF,
					CASE
						WHEN PED.CLIROT IS NULL THEN 'AGUARDANDO'
					ELSE CONVERT(VARCHAR, DATARM, 126)
					END AS AG_BDG
					FROM (
						--QTD MATERIAL (INICIO)
						SELECT TXT.CODFIL, CODPED, CAST(SUM(QUANTI)AS INT) AS TTPED, MATERIAL
						FROM (
							SELECT CODIGO,
							CASE
								WHEN PRO.CODIGO IN (23750, 23888, 23775, 23967, 24246, 24248)
									THEN 'COLA'
							ELSE 'BANDA / ACESSORIO'
							END AS 'MATERIAL'
							FROM WMSPRO PRO
						) AS DESCR
						LEFT JOIN PEDIDO_ARMAZENAGEM_TXT TXT ON DESCR.CODIGO=TXT.CODPRO
						WHERE TXT.CODPED IS NOT NULL
						GROUP BY TXT.CODFIL, CODPED, MATERIAL
						--QTD MATERIAL (FIM)
					) AS TTL
					LEFT JOIN WMSPED PED ON TTL.CODFIL=PED.CODFIL AND TTL.CODPED=PED.CODIGO
					LEFT JOIN WMSOSA OSA ON PED.CODFIL=OSA.FILPED AND PED.CODIGO=OSA.CODPED
					LEFT JOIN RODCLI CLI ON OSA.CODPRO=CLI.CODCLIFOR
					WHERE DATPED >='2023-07-17' AND PED.CODCTS = '153' AND OSA.SITUAC <> 'C'
					-- Nº OS - STATUS - CLI - SIT - DATE (FIM)
				) AS PED
				LEFT JOIN (
					SELECT CODFIL, CODIGO, COUNT(CODLOT) AS TTATE
					FROM WMSIPE 
					GROUP BY CODFIL, CODIGO
				) AS IPE 
				ON PED.CODFIL=IPE.CODFIL AND PED.PEDIDO=IPE.CODIGO
				-- QTD ATENDIDA NO PDIDO (FIM)
			) AS DDS
			LEFT JOIN (
				SELECT OSA.CODFIL AS FILOSA, OSA.CODOSA
				FROM WMSOSA OSA
				LEFT JOIN WMSIOL IOL ON OSA.CODFIL=IOL.FILOSA AND OSA.CODOSA=IOL.CODOSA
				WHERE OSA.CODCLIFOR = '6693556' AND IOL.CODPRO IS NOT NULL AND TIPDOC='S'
				GROUP BY OSA.CODFIL, OSA.CODOSA
			) AS IOL
			ON DDS.CODFIL=IOL.FILOSA AND DDS.OS=IOL.CODOSA
			--SEGUNDA CONFERENCIA (FINAL)
		) AS DOS
		LEFT JOIN (
			SELECT FILDOC, CODDOC, ARQTXT, TIPARQ, DATINC
			FROM LOG_INTEGRACAO_TXT
			WHERE TIPARQ = 'WMS06' AND ARQTXT IS NOT NULL
		) AS M51
		ON DOS.CODFIL=M51.FILDOC AND DOS.PEDIDO=M51.CODDOC
		--GERA ARQUIVO M51 (FIM)
	) AS VND
	LEFT JOIN (
		SELECT FILDOC, CODDOC, CODCLIFOR, SERIEN, NOTFIS
		FROM RODIRC 
		WHERE TIPDOC = 'P'
	) AS NFBD
	ON NFBD.FILDOC=VND.CODFIL AND NFBD.CODDOC=VND.PEDIDO
) AS VDB
--WHERE DATPED >= DATEADD(DAY, -30, GETDATE())
--WHERE RAZSOC LIKE '%RENOCAP%'
--WHERE M51 IS NULL
--WHERE CLIPED = '80121434'
--ORDER BY VDB.PEDIDO, VDB.RAZSOC