--CREATE VIEW VW_VEICULOS_SEM_OCO_FINALIZADORA_CAMP AS
SELECT DEV.*
FROM VW_ULTIMO_DOC_X_ENTRADA_VEICULO_CAMP DEV
WHERE DEV.TIPDOC='C' AND
DEV.PLACA NOT IN (
	SELECT DEV.PLACA
	FROM VW_ULTIMO_DOC_X_ENTRADA_VEICULO_CAMP DEV
	LEFT OUTER JOIN RODNFC NFC ON DEV.CODIGO=NFC.CODCON AND DEV.SERIE=NFC.SERCON AND DEV.FILIAL=NFC.CODFIL
	LEFT OUTER JOIN RODOCH OCH ON NFC.ID_NFC=OCH.ID_NFC
	WHERE DEV.TIPDOC='C' AND OCH.CODOCO IN (1, 138)
)

UNION ALL

SELECT DEV.*
FROM VW_ULTIMO_DOC_X_ENTRADA_VEICULO_CAMP DEV
WHERE DEV.TIPDOC='O' AND
DEV.PLACA NOT IN (
	SELECT DEV.PLACA
	FROM VW_ULTIMO_DOC_X_ENTRADA_VEICULO_CAMP DEV
	LEFT OUTER JOIN RODIOS IOS ON DEV.CODIGO=IOS.CODORD AND DEV.SERIE=IOS.SERORD AND DEV.FILIAL=IOS.FILORD
	LEFT OUTER JOIN RODOCH OCH ON IOS.ID_IOS=OCH.ID_NFC
	WHERE DEV.TIPDOC='O' AND OCH.CODOCO IN (1, 138)
)