--CREATE VIEW VW_WMS_INDICADOR_NOSHOW AS
SELECT TAB.RAZSOC, TAB.NOTFIS, TAB.DATA_AGENDA, SUM(TAB.TTATE) AS TOTAL_PRODUTOS,
CASE WHEN WIE.DATA_REF IS NULL THEN CAST(CURRENT_TIMESTAMP AS DATE) ELSE WIE.DATA_REF END AS DATA_REF,
DATEDIFF(DAY, TAB.DATA_AGENDA, CASE WHEN WIE.DATA_REF IS NULL THEN CAST(CURRENT_TIMESTAMP AS DATE) ELSE WIE.DATA_REF END) AS DIAS_EM_NOSHOW
FROM (
	SELECT VVB.RAZSOC, CAST(CAST(VVB.AG_BDG AS DATE) AS VARCHAR) AS DATA_AGENDA,
	SUBSTRING(VVB.NOTFIS, PATINDEX('%[^0]%', VVB.NOTFIS+'.'), LEN(VVB.NOTFIS)) AS NOTFIS,
	VVB.TTATE
	FROM VW_VENDA_BRIDGESTONE VVB
	WHERE VVB.LEITURA='M51 ENVIADO' AND VVB.AG_BDG<>'AGUARDANDO'
) AS TAB
LEFT OUTER JOIN VW_WMS_INDICADOR_EXPEDICAO WIE ON TAB.NOTFIS=WIE.NOTFIS
WHERE (WIE.DATA_REF IS NULL OR TAB.DATA_AGENDA < CASE WHEN WIE.DATA_REF IS NULL THEN CAST(CURRENT_TIMESTAMP AS DATE) ELSE WIE.DATA_REF END)
GROUP BY TAB.RAZSOC, TAB.NOTFIS, TAB.DATA_AGENDA, WIE.DATA_REF
--ORDER BY TAB.DATA_AGENDA, TAB.RAZSOC