--CREATE VIEW VW_WMS_INDICADOR_EXPEDICAO AS
SELECT RAZSOC, TIPPRO, SUM(CAST(QUANTI AS INT)) AS TOTAL, CODRMC,
SUBSTRING(NOTFIS, PATINDEX('%[^0]%', NOTFIS+'.'), LEN(NOTFIS)) AS NOTFIS,
CAST(DATA_REF AS VARCHAR) AS DATA_REF
FROM (
	SELECT 
		CASE GRU.DESCRI
			WHEN 'BRIDGESTONE BANDA' THEN 'BANDA'
			WHEN 'BRIDGESTONE COXIM' THEN 'COXIM'
			WHEN 'BRIDGESTONE EXTRUSADO' THEN 'COXIM'
			WHEN 'BRIDGESTONE HDSS' THEN 'COXIM'
			WHEN 'BRIDGESTONE LUBRIFICANTE' THEN 'COLA'
		END AS TIPPRO,
		IPE.QUANTI, CAST(RMC.DATREF AS DATE) AS DATA_REF, CLI.RAZSOC,
		CLI.CODCLIFOR, IRC.CODDOC, IRC.CODRMC, IRC.NOTFIS
	FROM RODRMC RMC
	LEFT OUTER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC
	LEFT OUTER JOIN WMSIPE IPE ON IRC.CODDOC=IPE.CODIGO AND IRC.FILDOC=IPE.CODFIL
	LEFT OUTER JOIN WMSPRO PRO ON IPE.CODPRO=PRO.CODIGO
	LEFT OUTER JOIN WMSGRU GRU ON PRO.CODGRU=GRU.CODGRU
	LEFT OUTER JOIN WMSPED PED ON IPE.CODIGO=PED.CODIGO AND IPE.CODFIL=PED.CODFIL
	LEFT OUTER JOIN WMSOSA OSA ON PED.CODIGO=OSA.CODPED AND PED.CODFIL=OSA.FILPED
	LEFT OUTER JOIN RODCLI CLI ON OSA.CODPRO=CLI.CODCLIFOR
	WHERE RMC.CODFIL=4 AND RMC.CODSETCL=8
) TAB
WHERE RAZSOC IS NOT NULL --DATA_REF='2023-10-16'
GROUP BY RAZSOC, CODRMC, TIPPRO, NOTFIS, DATA_REF
--ORDER BY RAZSOC

SELECT * FROM VW_WMS_INDICADOR_EXPEDICAO WHERE DATA_REF='2023-10-18'