--ALTER VIEW VW_WMS_INDICADOR_EXPEDICAO AS
SELECT RAZSOC, TIPPRO, SUM(CAST(QUANTI AS INT)) AS TOTAL, CODRMC,
SUBSTRING(NOTFIS, PATINDEX('%[^0]%', NOTFIS+'.'), LEN(NOTFIS)) AS NOTFIS,
CAST(DATA_REF AS VARCHAR) AS DATA_REF, CAST(DATA_AGENDA AS VARCHAR) AS DATA_AGENDA
FROM (
	SELECT 
		CASE GRU.DESCRI
			WHEN 'BRIDGESTONE BANDA' THEN 'BANDA'
			WHEN 'BRIDGESTONE COXIM' THEN 'COXIM'
			WHEN 'BRIDGESTONE EXTRUSADO' THEN 'COXIM'
			WHEN 'BRIDGESTONE HDSS' THEN 'COXIM'
			WHEN 'BRIDGESTONE LUBRIFICANTE' THEN 'COLA'
		END AS TIPPRO,
		IPE.QUANTI, CAST(RMC.DATREF AS DATE) AS DATA_REF, CLI.RAZSOC,
		CLI.CODCLIFOR, IRC.CODDOC, IRC.CODRMC, IRC.NOTFIS, CAST(PED.DATARM AS DATE) AS DATA_AGENDA
	FROM RODRMC RMC
	LEFT OUTER JOIN RODIRC IRC ON RMC.CODRMC=IRC.CODRMC AND RMC.CODFIL=IRC.FILRMC
	LEFT OUTER JOIN WMSIPE IPE ON IRC.CODDOC=IPE.CODIGO AND IRC.FILDOC=IPE.CODFIL
	LEFT OUTER JOIN WMSPRO PRO ON IPE.CODPRO=PRO.CODIGO
	LEFT OUTER JOIN WMSGRU GRU ON PRO.CODGRU=GRU.CODGRU
	LEFT OUTER JOIN WMSPED PED ON IPE.CODIGO=PED.CODIGO AND IPE.CODFIL=PED.CODFIL
	LEFT OUTER JOIN WMSOSA OSA ON PED.CODIGO=OSA.CODPED AND PED.CODFIL=OSA.FILPED
	LEFT OUTER JOIN RODCLI CLI ON OSA.CODPRO=CLI.CODCLIFOR
	WHERE RMC.CODFIL=4 AND RMC.CODSETCL=8
) TAB
WHERE RAZSOC IS NOT NULL --AND DATA_REF='2023-10-16'
GROUP BY RAZSOC, CODRMC, TIPPRO, NOTFIS, DATA_REF, DATA_AGENDA
--ORDER BY RAZSOC

SELECT * FROM VW_WMS_INDICADOR_EXPEDICAO WHERE DATA_REF>DATA_AGENDA AND DATA_AGENDA='2024-05-08'

SELECT TAB.RAZSOC, TAB.NOTFIS, TAB.DATA_AGENDA, SUM(TAB.TTATE) AS TOTAL_PRODUTOS, WIE.DATA_REF
FROM (
	SELECT VVB.RAZSOC, CAST(CAST(VVB.AG_BDG AS DATE) AS VARCHAR) AS DATA_AGENDA,
	SUBSTRING(VVB.NOTFIS, PATINDEX('%[^0]%', VVB.NOTFIS+'.'), LEN(VVB.NOTFIS)) AS NOTFIS,
	VVB.TTATE
	FROM VW_VENDA_BRIDGESTONE VVB
	WHERE VVB.LEITURA='M51 ENVIADO' AND VVB.AG_BDG<>'AGUARDANDO'
) AS TAB
LEFT OUTER JOIN VW_WMS_INDICADOR_EXPEDICAO WIE ON TAB.NOTFIS=WIE.NOTFIS
WHERE (WIE.DATA_REF IS NULL OR TAB.DATA_AGENDA<WIE.DATA_REF)
GROUP BY TAB.RAZSOC, TAB.NOTFIS, TAB.DATA_AGENDA, WIE.DATA_REF
ORDER BY TAB.DATA_AGENDA, TAB.RAZSOC

SELECT TOP 1000 *, SUBSTRING(NOTFIS, PATINDEX('%[^0]%', NOTFIS+'.'), LEN(NOTFIS)) AS NOTFIS FROM VW_VENDA_BRIDGESTONE WHERE RAZSOC LIKE 'PNEULANDIA%'

QTD. PEÇAS
CLIENTE
DATA ROMANEIO
DATA AGENDA

SELECT * FROM VW_VENDA_BRIDGESTONE